/** Maps Month 1 exercise display names to catalog slugs. */
export const MONTH1_EXERCISE_SLUG_MAP: Record<string, string> = {
  "Ab Wheel Rollout": "ab-wheel-rollout",
  "Alternating Dumbbell Curl": "alternating-dumbbell-curl",
  "Arnold Press": "arnold-press",
  "Assisted Pull-Up": "assisted-pull-up",
  "Back Squat": "back-squat",
  "Barbell Bench Press": "bench-press",
  "Barbell Curl": "barbell-curl",
  "Barbell Hip Thrust": "barbell-hip-thrust",
  "Barbell Romanian": "barbell-romanian",
  "Barbell Romanian Deadlift": "romanian-deadlift",
  "Barbell Row": "barbell-row",
  "Bayesian Cable Curl": "bayesian-curl",
  "Bear Crawl Hold": "bear-crawl-hold",
  "Belt Squat": "belt-squat",
  "Bench Dip": "bench-dip",
  "Bicycle Crunch": "bicycle-crunch",
  "Bulgarian Split Squat": "bulgarian-split-squat",
  "Cable Anti-Rotation Hold": "pallof-press",
  "Cable Crossover": "cable-crossover",
  "Cable Crunch": "cable-crunch",
  "Cable Curl": "cable-curl",
  "Cable Face Pull Row": "face-pull",
  "Cable Fly": "cable-fly",
  "Cable Glute Kickback": "cable-glute-kickback",
  "Cable Hammer Curl": "cable-hammer-curl",
  "Cable Hip Abduction": "cable-hip-abduction",
  "Cable Lateral Raise": "cable-lateral-raise",
  "Cable Lift": "wood-chop",
  "Cable Pull-Through": "cable-pull-through",
  "Cable Reverse Crunch": "reverse-crunch",
  "Cable Rope Curl": "cable-rope-curl",
  "Cable Triceps Kickback": "triceps-kickback",
  "Cable Wood Chop": "wood-chop",
  "Cable Y-Raise": "cable-y-raise",
  "Captain Chair Knee Raise": "captain-chair-knee-raise",
  "Chest-Supported Dumbbell Row": "chest-supported-row",
  "Chest-Supported Machine Row": "chest-supported-row",
  "Chin-Up": "chin-up",
  "Close-Grip Bench Press": "close-grip-bench-press",
  "Close-Grip Pulldown": "close-grip-lat-pulldown",
  "Close-Grip Push-Up": "close-grip-push-up",
  "Cross-Body Cable Triceps Extension": "single-arm-triceps-extension",
  "Cross-Body Hammer Curl": "cross-body-hammer-curl",
  "Dead Bug": "dead-bug",
  "Deadlift": "deadlift",
  "Decline Barbell Bench Press": "decline-barbell-bench-press",
  "Decline Dumbbell Bench Press": "decline-dumbbell-bench-press",
  "Decline Sit-Up": "decline-sit-up",
  "Deficit Push-Up": "push-up",
  "Diamond Push-Up": "diamond-push-up",
  "Dip Machine": "dip-machine",
  "Donkey Calf Raise": "donkey-calf-raise",
  "Drag Curl": "drag-curl",
  "Dragon Flag Regression": "dragon-flag",
  "Dumbbell Bench Press": "dumbbell-bench-press",
  "Dumbbell Concentration Curl": "concentration-curl",
  "Dumbbell Fly": "dumbbell-fly",
  "Dumbbell Lateral Raise": "lateral-raise",
  "Dumbbell Overhead Triceps Extension": "overhead-triceps-extension",
  "Dumbbell Pullover": "dumbbell-pullover",
  "Dumbbell Push Press": "dumbbell-push-press",
  "Dumbbell Rear Delt Fly": "reverse-fly",
  "Dumbbell Reverse Lunge": "reverse-lunge",
  "Dumbbell Romanian Deadlift": "dumbbell-romanian-deadlift",
  "Dumbbell Step-Up": "step-up",
  "Dumbbell Walking Lunge": "walking-lunge",
  "EZ-Bar Curl": "ez-bar-curl",
  "EZ-Bar Skull Crusher": "skull-crusher",
  "Face Pull": "face-pull",
  "Farmer Carry": "farmer-carry",
  "Flat Barbell Bench Press": "bench-press",
  "Flat Dumbbell Bench Press": "dumbbell-bench-press",
  "Frog Pump": "frog-pump",
  "Front Squat": "front-squat",
  "Front-Foot Elevated Split Squat": "bulgarian-split-squat",
  "Glute Bridge": "glute-bridge",
  "Glute-Ham Raise": "glute-ham-raise",
  "Goblet Squat": "goblet-squat",
  "Good Morning": "good-morning",
  "Hack Squat": "hack-squat",
  "Half-Kneeling Pallof Press": "pallof-press",
  "Hammer Curl": "hammer-curl",
  "Hammer Strength Chest Press": "machine-chest-press",
  "Hanging Knee Raise": "hanging-knee-raise",
  "Hanging Leg Raise": "hanging-leg-raise",
  "High Cable Curl": "high-cable-curl",
  "High Cable Fly": "cable-fly",
  "Hip Thrust Machine": "hip-thrust-machine",
  "Hollow Body Hold": "hollow-hold",
  "Incline Barbell Bench Press": "incline-barbell-bench-press",
  "Incline Cable Press": "incline-cable-press",
  "Incline Dumbbell Bench Press": "incline-dumbbell-press",
  "Incline Dumbbell Curl": "incline-dumbbell-curl",
  "Incline Dumbbell Press": "incline-dumbbell-press",
  "Incline Hammer Curl": "incline-hammer-curl",
  "Incline Machine Chest Press": "machine-chest-press",
  "Inverted Row": "inverted-row",
  "JM Press": "jm-press",
  "Landmine Press": "landmine-press",
  "Landmine Rotation": "landmine-rotation",
  "Lat Pulldown": "lat-pulldown",
  "Lean-Away Cable Lateral Raise": "cable-lateral-raise",
  "Leg Extension": "leg-extension",
  "Leg Press": "leg-press",
  "Leg Press Calf Raise": "leg-press-calf-raise",
  "Long-Lever Plank": "plank",
  "Low-to-High Cable Fly": "cable-fly",
  "Lying Dumbbell": "lying-dumbbell",
  "Lying Dumbbell Triceps Extension": "overhead-triceps-extension",
  "Lying Leg Curl": "lying-leg-curl",
  "Machine Chest Press": "machine-chest-press",
  "Machine Curl": "machine-curl",
  "Machine High Row": "machine-row",
  "Machine Lateral Raise": "lateral-raise",
  "Machine Row": "machine-row",
  "Machine Shoulder Press": "machine-shoulder-press",
  "Meadows Row": "meadows-row",
  "Mountain Climber": "mountain-climber",
  "Neutral-Grip Pull-Up": "neutral-grip-pull-up",
  "Neutral-Grip Pulldown": "lat-pulldown",
  "Nordic Hamstring Curl": "nordic-hamstring-curl",
  "One-Arm Cable Row": "single-arm-cable-row",
  "Overhead Rope Triceps Extension": "overhead-triceps-extension",
  "Pallof Press": "pallof-press",
  "Paused Barbell Bench Press": "paused-barbell-bench-press",
  "Paused Front Squat": "front-squat",
  "Pec Deck Fly": "pec-deck-fly",
  "Pendlay Row": "pendlay-row",
  "Plank": "plank",
  "Preacher Curl": "preacher-curl",
  "Pull-Up": "pull-up",
  "Push-Up": "push-up",
  "Rack Pull": "rack-pull",
  "Rear Delt Cable Fly": "reverse-fly",
  "Reverse Crunch": "reverse-crunch",
  "Reverse Curl": "reverse-curl",
  "Reverse Lunge": "reverse-lunge",
  "Reverse Pec Deck": "reverse-fly",
  "Reverse-Grip Triceps Pushdown": "triceps-pushdown",
  "Romanian Deadlift": "romanian-deadlift",
  "Rope Hammer Curl": "hammer-curl",
  "Rope Overhead Triceps Extension": "overhead-triceps-extension",
  "Rope Triceps Pushdown": "triceps-pushdown",
  "Russian Twist": "russian-twist",
  "Seal Row": "seal-row",
  "Seated Barbell Overhead Press": "overhead-press",
  "Seated Cable Row": "seated-cable-row",
  "Seated Calf Raise": "seated-calf-raise",
  "Seated Dumbbell Shoulder Press": "seated-dumbbell-shoulder-press",
  "Seated Leg Curl": "seated-leg-curl",
  "Side Plank": "side-plank",
  "Side Plank Reach- Through": "side-plank-reach-through",
  "Side Plank Reach-Through": "side-plank",
  "Single-Arm Cable Press": "single-arm-cable-press",
  "Single-Arm Cable Triceps Extension": "single-arm-triceps-extension",
  "Single-Arm Dumbbell": "single-arm-dumbbell",
  "Single-Arm Dumbbell Lateral Raise": "lateral-raise",
  "Single-Arm Dumbbell Row": "single-arm-dumbbell-row",
  "Single-Arm Lat Pulldown": "single-arm-lat-pulldown",
  "Single-Arm Overhead Dumbbell Extension": "overhead-triceps-extension",
  "Single-Leg Romanian Deadlift": "single-leg-romanian-deadlift",
  "Single-Leg Standing Calf Raise": "single-leg-calf-raise",
  "Sissy Squat": "sissy-squat",
  "Skull Crusher": "skull-crusher",
  "Smith Machine": "smith-machine",
  "Smith Machine Calf Raise": "smith-machine-calf-raise",
  "Smith Machine Shoulder Press": "machine-shoulder-press",
  "Smith Machine Squat": "smith-machine-squat",
  "Spider Curl": "spider-curl",
  "Stability Ball Crunch": "stability-ball-crunch",
  "Standing Barbell Overhead Press": "overhead-press",
  "Standing Cable Crunch": "cable-crunch",
  "Standing Calf Raise": "standing-calf-raise",
  "Standing Single-Leg Curl": "standing-leg-curl",
  "Stir-the-Pot": "stir-the-pot",
  "Straight-Arm Pulldown": "straight-arm-pulldown",
  "Straight-Arm Rope Pulldown": "straight-arm-pulldown",
  "Suitcase Carry": "suitcase-carry",
  "Sumo Deadlift": "sumo-deadlift",
  "T-Bar Row": "t-bar-row",
  "Toe Touch Crunch": "toe-touch-crunch",
  "Toes-to-Bar": "toes-to-bar",
  "Trap Bar Deadlift": "trap-bar-deadlift",
  "Underhand Lat Pulldown": "underhand-lat-pulldown",
  "Upright Row": "upright-row",
  "Walking Lunge": "walking-lunge",
  "Weighted Bench Dip": "bench-dip",
  "Weighted Chin-Up": "chin-up",
  "Weighted Crunch": "crunch",
  "Weighted Dead Bug": "dead-bug",
  "Weighted Dip": "dip",
  "Weighted Plank": "plank",
  "Weighted Pull-Up": "pull-up",
  "Weighted Ring Push- Up": "weighted-ring-push-up",
  "Weighted Ring Push-Up": "push-up",
  "Wide-Grip Cable Row": "seated-cable-row",
  "Wide-Grip Lat Pulldown": "lat-pulldown",
  "Zercher Squat": "zercher-squat",
  "Zottman Curl": "zottman-curl",
};