import assert from 'node:assert/strict';
import test from 'node:test';

import { resolveExerciseFormGuide } from './exerciseFormGuides';
import { resolveExerciseGuideSections } from './exerciseGuideSections';
import type { Exercise } from '@/types';
import type { MovementCategory } from '@/types/common';

function exercise(name: string, category: MovementCategory, slug?: string): Exercise {
  return {
    id: name,
    name,
    slug,
    category,
    exerciseType: 'strength',
    equipment: 'other',
    muscleGroups: ['general'],
    isSystem: false,
    createdAt: '2026-08-02T00:00:00.000Z',
  };
}

test('an uncovered custom exercise still gets a complete, honestly-labelled guide', () => {
  const guide = resolveExerciseFormGuide(exercise('My Garage Belt Machine', 'other'));
  assert.ok(guide);
  assert.equal(guide.source, 'category');
  assert.equal(guide.isGeneral, true);

  const sections = resolveExerciseGuideSections(guide);
  assert.ok(sections.phases.length >= 3);
  assert.ok(sections.breathing);
  assert.ok(sections.avoid.length >= 1);
  assert.ok(sections.easier.length >= 1);
  assert.ok(sections.harder.length >= 1);
});

test('every movement category has setup, breathing, mistakes, and scaling guidance', () => {
  const categories: MovementCategory[] = [
    'push',
    'pull',
    'squat',
    'hinge',
    'core',
    'cardio',
    'carry',
    'other',
  ];

  for (const category of categories) {
    const guide = resolveExerciseFormGuide(exercise(`Unlisted ${category} variation`, category));
    assert.ok(guide, category);
    const sections = resolveExerciseGuideSections(guide);
    assert.ok(sections.phases.length > 0, `${category}: phases`);
    assert.ok(sections.breathing, `${category}: breathing`);
    assert.ok(sections.avoid.length > 0, `${category}: avoid`);
    assert.ok(sections.easier.length > 0, `${category}: easier`);
    assert.ok(sections.harder.length > 0, `${category}: harder`);
  }
});

test('a known exercise remains exercise-specific, not a general fallback', () => {
  const guide = resolveExerciseFormGuide(exercise('Side Plank', 'core', 'side-plank'));
  assert.ok(guide);
  assert.notEqual(guide.source, 'category');
  assert.notEqual(guide.isGeneral, true);

  const sections = resolveExerciseGuideSections(guide);
  assert.match(sections.phases.map((phase) => phase.detail).join(' '), /forearm|hip/i);
  assert.ok(sections.breathing);
  assert.ok(sections.avoid.length > 0);
});

test('database-authored instructions are enriched without losing their exercise-specific status', () => {
  const target = exercise('Coach Special Row', 'pull');
  target.instructions = ['Set your chest against the pad.', 'Pull the handles toward your ribs.'].join('\n');

  const guide = resolveExerciseFormGuide(target);
  assert.ok(guide);
  assert.equal(guide.source, 'instructions');
  assert.notEqual(guide.isGeneral, true);

  const sections = resolveExerciseGuideSections(guide);
  assert.equal(sections.phases.length, 2);
  assert.ok(sections.breathing);
  assert.ok(sections.avoid.length > 0);
});

test('support lines are routed out of the movement steps', () => {
  const guide = resolveExerciseFormGuide(exercise('Unknown Push Machine', 'push'));
  const sections = resolveExerciseGuideSections(guide);

  assert.equal(
    sections.phases.some((phase) =>
      /^(avoid|easier|harder|inhale|exhale)\b/i.test(phase.detail),
    ),
    false,
  );
});

test('unreviewed autogenerated instructions are not shown as exercise-specific guidance', () => {
  // The generated draft for this exercise says to pick up a load and walk — unsafe nonsense for
  // an assault bike. Until a guide is reviewed, the cardio fallback is honest and correct.
  const guide = resolveExerciseFormGuide(
    exercise('Assault Bike Sprint', 'cardio', 'assault-bike-sprint'),
  );
  assert.ok(guide);
  assert.equal(guide.source, 'category');
  assert.equal(guide.isGeneral, true);

  const content = guide.steps.join(' ');
  assert.match(content, /rhythm|intensity|pace|breathing/i);
  assert.doesNotMatch(content, /pick up the load|walk the prescribed distance/i);
});

test('encyclopedia substring matches are not treated as exact form guides', () => {
  const guide = resolveExerciseFormGuide(
    exercise('Side Plank With Reach Variation', 'core', 'side-plank-with-reach-variation'),
  );
  assert.ok(guide);
  assert.equal(guide.source, 'category');
  assert.equal(guide.isGeneral, true);
});
