import type { LiftFlowInsight } from './types';

export const ALL_INSIGHTS: LiftFlowInsight[] = [
  // ── Training (20) ──────────────────────────────────────────
  {
    id: 'training-progressive-overload',
    category: 'training',
    icon: '📈',
    headline: 'Progressive overload drives adaptation',
    body: 'Muscles grow when they are challenged beyond their current capacity. Gradually increasing weight, reps, or sets signals your body to build stronger tissue over time.',
  },
  {
    id: 'training-compound-movements',
    category: 'training',
    icon: '🏋️',
    headline: 'Compound lifts recruit the most muscle',
    body: 'Squats, deadlifts, presses, and rows engage multiple joints and muscle groups simultaneously. They deliver the greatest stimulus per minute in the gym.',
  },
  {
    id: 'training-rpe',
    category: 'training',
    icon: '🎯',
    headline: 'RPE helps you train with precision',
    body: 'Rate of Perceived Exertion scales effort from 1 to 10. Leaving 1–2 reps in reserve on most sets balances growth stimulus with recovery capacity.',
  },
  {
    id: 'training-deload',
    category: 'training',
    icon: '🔄',
    headline: 'Deload weeks prevent accumulated fatigue',
    body: 'Reducing volume or intensity every 4–8 weeks lets your nervous system and connective tissue recover. You often come back stronger after a planned deload.',
  },
  {
    id: 'training-tempo',
    category: 'training',
    icon: '⏱️',
    headline: 'Tempo controls time under tension',
    body: 'Slowing the eccentric phase increases mechanical tension on muscle fibers. A 2–3 second lowering phase can boost hypertrophy without adding load.',
  },
  {
    id: 'training-rest-periods',
    category: 'training',
    icon: '⏸️',
    headline: 'Rest periods shape your training outcome',
    body: 'Shorter rest (60–90 s) favors metabolic stress and endurance. Longer rest (2–3 min) on heavy compounds preserves strength output for quality reps.',
  },
  {
    id: 'training-warmup',
    category: 'training',
    icon: '🔥',
    headline: 'Warm-up sets prime your nervous system',
    body: 'Gradually ramping weight before working sets improves force production and reduces injury risk. Two to four warm-up sets on heavy lifts is usually sufficient.',
  },
  {
    id: 'training-frequency',
    category: 'training',
    icon: '📅',
    headline: 'Training frequency matters for growth',
    body: 'Research shows training each muscle group 2–3 times per week often outperforms once-weekly sessions. Total weekly volume is what matters most.',
  },
  {
    id: 'training-mind-muscle',
    category: 'training',
    icon: '🧠',
    headline: 'Mind-muscle connection enhances activation',
    body: 'Consciously focusing on the target muscle during isolation work increases EMG activity. This internal cueing can improve hypertrophy on accessory movements.',
  },
  {
    id: 'training-periodization',
    category: 'training',
    icon: '📊',
    headline: 'Periodization prevents plateaus',
    body: 'Cycling through phases of higher volume, intensity, and recovery keeps your body adapting. Linear and undulating models both work when applied consistently.',
  },
  {
    id: 'training-unilateral',
    category: 'training',
    icon: '🦵',
    headline: 'Unilateral work corrects imbalances',
    body: 'Single-leg and single-arm exercises expose side-to-side strength gaps. Addressing asymmetries reduces injury risk and improves bilateral lift performance.',
  },
  {
    id: 'training-eccentric',
    category: 'training',
    icon: '⬇️',
    headline: 'Eccentric loading builds unique strength',
    body: 'Muscles can handle roughly 20–40% more load during the lowering phase. Controlled eccentrics create micro-damage that drives repair and growth.',
  },
  {
    id: 'training-volume-landmarks',
    category: 'training',
    icon: '📐',
    headline: 'Volume landmarks guide effective training',
    body: 'Most lifters grow well with 10–20 hard sets per muscle group per week. Below minimum effective volume, gains stall; beyond maximum recoverable volume, fatigue accumulates.',
  },
  {
    id: 'training-exercise-selection',
    category: 'training',
    icon: '🛠️',
    headline: 'Exercise selection should match your goals',
    body: 'Choose movements that load the target muscle through a full range of motion with manageable joint stress. The best exercise is one you can perform consistently and progressively.',
  },
  {
    id: 'training-failure',
    category: 'training',
    icon: '💥',
    headline: 'Training to failure has diminishing returns',
    body: 'Reaching absolute failure on every set increases fatigue without proportional growth benefit. Reserve failure training for isolation exercises and final sets.',
  },
  {
    id: 'training-grip-strength',
    category: 'training',
    icon: '🤜',
    headline: 'Grip strength limits pulling performance',
    body: 'A weak grip caps deadlift and row loads before your back fatigues. Dedicated grip work and strategic use of straps on high-rep back days can unlock progress.',
  },
  {
    id: 'training-full-rom',
    category: 'training',
    icon: '↕️',
    headline: 'Full range of motion maximizes stimulus',
    body: 'Training through a complete range under load produces greater muscle activation than partial reps. Depth and stretch at the bottom of each rep matter for hypertrophy.',
  },
  {
    id: 'training-cluster-sets',
    category: 'training',
    icon: '🔗',
    headline: 'Cluster sets maintain power output',
    body: 'Breaking a set into mini-clusters with brief rest preserves bar speed and technique on heavy lifts. This method builds strength without sacrificing rep quality.',
  },
  {
    id: 'training-auto-regulation',
    category: 'training',
    icon: '🎚️',
    headline: 'Auto-regulation adapts to daily readiness',
    body: 'Some days you are stronger; some days you are not. Adjusting load based on bar speed or RPE lets you train hard when fresh and pull back when fatigued.',
  },
  {
    id: 'training-consistency',
    category: 'training',
    icon: '✅',
    headline: 'Consistency beats intensity spikes',
    body: 'Showing up and executing a solid program for months outperforms occasional all-out sessions. Sustainable training frequency is the strongest predictor of long-term results.',
  },

  // ── Nutrition (18) ─────────────────────────────────────────
  {
    id: 'nutrition-protein-synthesis',
    category: 'nutrition',
    icon: '🥩',
    headline: 'Protein fuels muscle repair',
    body: 'Amino acids from dietary protein provide the building blocks for muscle protein synthesis. Aim for 1.6–2.2 g per kg of body weight daily when training hard.',
  },
  {
    id: 'nutrition-leucine',
    category: 'nutrition',
    icon: '🧬',
    headline: 'Leucine triggers the growth signal',
    body: 'The branched-chain amino acid leucine activates mTOR, the primary pathway for muscle building. Each meal should contain roughly 2–3 g of leucine to maximize synthesis.',
  },
  {
    id: 'nutrition-pre-workout-carbs',
    category: 'nutrition',
    icon: '🍌',
    headline: 'Pre-workout carbs fuel performance',
    body: 'Carbohydrates top off muscle glycogen stores before training. A meal with 30–60 g of carbs 1–2 hours before lifting supports higher training volume.',
  },
  {
    id: 'nutrition-hydration',
    category: 'nutrition',
    icon: '💧',
    headline: 'Hydration affects strength and focus',
    body: 'Even mild dehydration of 2% body weight can reduce power output and cognitive performance. Drink consistently throughout the day, not just during workouts.',
  },
  {
    id: 'nutrition-creatine',
    category: 'nutrition',
    icon: '⚡',
    headline: 'Creatine is the most studied supplement',
    body: 'Creatine monohydrate increases phosphocreatine stores, boosting ATP regeneration during high-intensity efforts. Five grams daily improves strength and lean mass over time.',
  },
  {
    id: 'nutrition-post-workout',
    category: 'nutrition',
    icon: '🥤',
    headline: 'Post-workout nutrition supports recovery',
    body: 'Consuming protein and carbohydrates within a few hours of training replenishes glycogen and kickstarts repair. The anabolic window is wider than once believed, but timing still helps.',
  },
  {
    id: 'nutrition-fiber',
    category: 'nutrition',
    icon: '🥦',
    headline: 'Fiber supports gut health and satiety',
    body: 'Dietary fiber slows digestion and promotes stable blood sugar during cuts. Aim for 25–35 g daily from vegetables, fruits, and whole grains.',
  },
  {
    id: 'nutrition-meal-timing',
    category: 'nutrition',
    icon: '🕐',
    headline: 'Meal timing is secondary to total intake',
    body: 'Total daily calories and protein matter more than precise meal timing for body composition. Spread protein across 3–5 meals for sustained amino acid availability.',
  },
  {
    id: 'nutrition-caloric-surplus',
    category: 'nutrition',
    icon: '📈',
    headline: 'A modest surplus supports muscle gain',
    body: 'Building muscle efficiently requires a caloric surplus of roughly 200–400 kcal above maintenance. Larger surpluses add unnecessary fat without accelerating muscle growth.',
  },
  {
    id: 'nutrition-micronutrients',
    category: 'nutrition',
    icon: '💊',
    headline: 'Micronutrients power cellular function',
    body: 'Vitamins and minerals support energy metabolism, bone health, and immune function. A varied diet of whole foods covers most needs; deficiencies can impair performance.',
  },
  {
    id: 'nutrition-omega3',
    category: 'nutrition',
    icon: '🐟',
    headline: 'Omega-3s reduce exercise-induced inflammation',
    body: 'EPA and DHA fatty acids modulate inflammatory responses after hard training. Regular intake from fatty fish or supplementation may support joint health and recovery.',
  },
  {
    id: 'nutrition-electrolytes',
    category: 'nutrition',
    icon: '🧂',
    headline: 'Electrolytes maintain muscle contraction',
    body: 'Sodium, potassium, and magnesium regulate nerve signals and fluid balance. Replacing electrolytes during long or sweaty sessions prevents cramping and fatigue.',
  },
  {
    id: 'nutrition-caffeine',
    category: 'nutrition',
    icon: '☕',
    headline: 'Caffeine enhances acute performance',
    body: 'Caffeine blocks adenosine receptors, reducing perceived effort and improving focus. Doses of 3–6 mg per kg body weight taken 30–60 minutes pre-workout boost power output.',
  },
  {
    id: 'nutrition-alcohol',
    category: 'nutrition',
    icon: '🍺',
    headline: 'Alcohol impairs recovery and protein synthesis',
    body: 'Even moderate alcohol intake suppresses muscle protein synthesis and disrupts sleep architecture. Limiting intake around training days protects your hard-earned progress.',
  },
  {
    id: 'nutrition-whole-foods',
    category: 'nutrition',
    icon: '🥗',
    headline: 'Whole foods provide synergistic nutrients',
    body: 'Minimally processed foods deliver fiber, phytonutrients, and satiety that supplements cannot replicate. Build your diet around whole food sources first.',
  },
  {
    id: 'nutrition-diet-breaks',
    category: 'nutrition',
    icon: '🍽️',
    headline: 'Diet breaks help sustain long cuts',
    body: 'Planned periods at maintenance calories reverse metabolic adaptation and reduce diet fatigue. One to two weeks at maintenance every 8–12 weeks of cutting can improve adherence.',
  },
  {
    id: 'nutrition-tracking',
    category: 'nutrition',
    icon: '📝',
    headline: 'Tracking reveals hidden patterns',
    body: 'Logging food intake for even a few weeks builds awareness of portion sizes and macro balance. You cannot optimize what you do not measure.',
  },
  {
    id: 'nutrition-sleep-appetite',
    category: 'nutrition',
    icon: '😴',
    headline: 'Sleep deprivation increases hunger hormones',
    body: 'Short sleep raises ghrelin and lowers leptin, driving cravings for calorie-dense foods. Prioritizing sleep is one of the most effective nutrition strategies available.',
  },

  // ── Recovery (17) ──────────────────────────────────────────
  {
    id: 'recovery-sleep-growth',
    category: 'recovery',
    icon: '🌙',
    headline: 'Sleep is when muscles actually grow',
    body: 'Growth hormone peaks during deep sleep stages, driving tissue repair and adaptation. Seven to nine hours of quality sleep is non-negotiable for serious lifters.',
  },
  {
    id: 'recovery-active-recovery',
    category: 'recovery',
    icon: '🚶',
    headline: 'Active recovery beats complete rest',
    body: 'Light movement like walking or easy cycling increases blood flow without adding training stress. Active recovery days reduce soreness faster than sitting still.',
  },
  {
    id: 'recovery-hrv',
    category: 'recovery',
    icon: '❤️',
    headline: 'HRV reflects your nervous system state',
    body: 'Heart rate variability measures the balance between sympathetic and parasympathetic activity. Consistently low HRV may signal you need more rest or less volume.',
  },
  {
    id: 'recovery-foam-rolling',
    category: 'recovery',
    icon: '🧴',
    headline: 'Foam rolling improves short-term mobility',
    body: 'Self-myofascial release temporarily increases range of motion and reduces perceived soreness. Use foam rolling as a warm-up tool rather than a standalone recovery method.',
  },
  {
    id: 'recovery-stretching',
    category: 'recovery',
    icon: '🤸',
    headline: 'Static stretching belongs after training',
    body: 'Holding stretches post-workout can reduce muscle stiffness without impairing strength. Pre-workout static stretching may temporarily reduce power output.',
  },
  {
    id: 'recovery-rest-days',
    category: 'recovery',
    icon: '🛋️',
    headline: 'Rest days are productive training days',
    body: 'Muscle protein synthesis remains elevated 24–48 hours after training. Rest days allow repair processes to complete before the next stimulus.',
  },
  {
    id: 'recovery-cold-exposure',
    category: 'recovery',
    icon: '🧊',
    headline: 'Cold exposure reduces acute inflammation',
    body: 'Ice baths and cold showers blunt inflammatory signaling and soreness after intense sessions. Avoid cold immediately post-hypertrophy training, as it may blunt adaptation.',
  },
  {
    id: 'recovery-heat-therapy',
    category: 'recovery',
    icon: '♨️',
    headline: 'Heat therapy promotes blood flow',
    body: 'Saunas and heat packs increase circulation and may reduce muscle stiffness. Regular sauna use is associated with improved cardiovascular health and recovery markers.',
  },
  {
    id: 'recovery-massage',
    category: 'recovery',
    icon: '💆',
    headline: 'Massage aids perceived recovery',
    body: 'Manual therapy reduces perceived muscle soreness and can improve range of motion. While effects on performance are modest, the psychological benefit supports consistency.',
  },
  {
    id: 'recovery-stress-cortisol',
    category: 'recovery',
    icon: '😰',
    headline: 'Chronic stress elevates cortisol',
    body: 'Sustained high cortisol breaks down muscle tissue and impairs sleep quality. Managing life stress is as important as managing training stress for recovery.',
  },
  {
    id: 'recovery-overtraining',
    category: 'recovery',
    icon: '⚠️',
    headline: 'Overtraining syndrome is real but rare',
    body: 'Persistent fatigue, declining performance, and mood changes may indicate non-functional overreaching. Reducing volume and prioritizing sleep usually resolves symptoms within weeks.',
  },
  {
    id: 'recovery-doms',
    category: 'recovery',
    icon: '🔴',
    headline: 'DOMS peaks 24–72 hours post-training',
    body: 'Delayed onset muscle soreness results from unfamiliar eccentric loading, not lactic acid. It diminishes as your body adapts to repeated movement patterns.',
  },
  {
    id: 'recovery-naps',
    category: 'recovery',
    icon: '💤',
    headline: 'Short naps boost alertness and recovery',
    body: 'A 20–30 minute nap improves cognitive function and can supplement insufficient nighttime sleep. Longer naps may cause sleep inertia and disrupt nighttime rest.',
  },
  {
    id: 'recovery-mobility',
    category: 'recovery',
    icon: '🔄',
    headline: 'Daily mobility preserves joint health',
    body: 'Regular mobility work maintains the range of motion needed for safe, effective lifting. Ten minutes of targeted drills before training reduces compensatory movement patterns.',
  },
  {
    id: 'recovery-breathing',
    category: 'recovery',
    icon: '🌬️',
    headline: 'Breathwork activates the parasympathetic system',
    body: 'Slow, diaphragmatic breathing lowers heart rate and cortisol within minutes. Box breathing or 4-7-8 patterns after training accelerate the shift from fight-or-flight to recovery.',
  },
  {
    id: 'recovery-contrast-therapy',
    category: 'recovery',
    icon: '🔀',
    headline: 'Contrast therapy alternates hot and cold',
    body: 'Switching between heat and cold exposure creates a pumping effect in blood vessels. This may reduce soreness, though evidence for performance benefits remains mixed.',
  },
  {
    id: 'recovery-nutrition-timing',
    category: 'recovery',
    icon: '🍳',
    headline: 'Recovery nutrition starts before you sleep',
    body: 'A protein-rich meal or shake before bed provides amino acids during overnight fasting. Casein protein digests slowly, supporting muscle repair through the night.',
  },

  // ── Motivation (17) ────────────────────────────────────────
  {
    id: 'motivation-habit-stacking',
    category: 'motivation',
    icon: '📌',
    headline: 'Stack habits onto existing routines',
    body: 'Linking a new behavior to an established one leverages automatic triggers. Pairing gym bag prep with your morning coffee makes training feel effortless over time.',
  },
  {
    id: 'motivation-identity',
    category: 'motivation',
    icon: '🪞',
    headline: 'Identity-based goals outlast outcome goals',
    body: 'Thinking "I am a lifter" rather than "I want to lose weight" creates intrinsic motivation. Identity shifts make skipping sessions feel inconsistent with who you are.',
  },
  {
    id: 'motivation-small-wins',
    category: 'motivation',
    icon: '🏆',
    headline: 'Small wins build momentum',
    body: 'Celebrating incremental progress—an extra rep, a consistent week—releases dopamine that reinforces the habit loop. Momentum compounds faster than motivation alone.',
  },
  {
    id: 'motivation-accountability',
    category: 'motivation',
    icon: '🤝',
    headline: 'Accountability doubles adherence rates',
    body: 'Sharing goals with a training partner or coach increases follow-through significantly. External commitment devices work especially well during low-motivation periods.',
  },
  {
    id: 'motivation-environment',
    category: 'motivation',
    icon: '🏠',
    headline: 'Design your environment for success',
    body: 'Removing friction—laying out gym clothes, meal prepping on Sunday—makes the right choice the easy choice. Willpower is finite; environment design is renewable.',
  },
  {
    id: 'motivation-intrinsic',
    category: 'motivation',
    icon: '💡',
    headline: 'Intrinsic motivation sustains long-term effort',
    body: 'People who train because they enjoy the process maintain habits far longer than those driven solely by appearance goals. Find aspects of training you genuinely love.',
  },
  {
    id: 'motivation-process-outcome',
    category: 'motivation',
    icon: '🎯',
    headline: 'Focus on process, not just outcomes',
    body: 'Outcome goals like "lose 10 kg" are motivating but uncontrollable day to day. Process goals like "train four times this week" keep you engaged regardless of scale fluctuations.',
  },
  {
    id: 'motivation-visualization',
    category: 'motivation',
    icon: '👁️',
    headline: 'Mental rehearsal primes performance',
    body: 'Visualizing successful lifts activates similar neural pathways as physical practice. Spending two minutes before a heavy set imagining perfect execution improves confidence and focus.',
  },
  {
    id: 'motivation-social-support',
    category: 'motivation',
    icon: '👥',
    headline: 'Social support buffers setbacks',
    body: 'Training communities provide encouragement during plateaus and celebrate milestones. Surrounding yourself with people who share your values makes consistency feel natural.',
  },
  {
    id: 'motivation-tracking-progress',
    category: 'motivation',
    icon: '📊',
    headline: 'Visible progress fuels motivation',
    body: 'Logging workouts reveals trends invisible in daily mirror checks. Reviewing eight weeks of training data often shows progress that felt absent in the moment.',
  },
  {
    id: 'motivation-setbacks',
    category: 'motivation',
    icon: '🔄',
    headline: 'Setbacks are data, not failure',
    body: 'Missing a week or regressing on a lift is normal in any long training career. Reframing setbacks as information about recovery needs prevents all-or-nothing thinking.',
  },
  {
    id: 'motivation-morning-routine',
    category: 'motivation',
    icon: '🌅',
    headline: 'Morning training reduces decision fatigue',
    body: 'Scheduling workouts early eliminates the chance that daily obligations displace training. Morning exercisers report higher long-term adherence in population studies.',
  },
  {
    id: 'motivation-smart-goals',
    category: 'motivation',
    icon: '📋',
    headline: 'Specific goals produce specific results',
    body: 'Vague goals like "get fit" lack direction. SMART goals—specific, measurable, achievable, relevant, time-bound—create clear milestones that guide daily decisions.',
  },
  {
    id: 'motivation-enjoyment',
    category: 'motivation',
    icon: '😊',
    headline: 'Enjoyment predicts long-term adherence',
    body: 'Programs you dislike will not survive six months regardless of their efficiency. Choosing exercises and splits you look forward to is a valid programming strategy.',
  },
  {
    id: 'motivation-plateau-mindset',
    category: 'motivation',
    icon: '🧗',
    headline: 'Plateaus are invitations to adapt',
    body: 'Stalled progress means your body has adapted to the current stimulus. Plateaus signal it is time to change variables—not evidence that you have reached your genetic limit.',
  },
  {
    id: 'motivation-comparison',
    category: 'motivation',
    icon: '🚫',
    headline: 'Comparison steals satisfaction from progress',
    body: 'Social media showcases others\' peak moments, not their daily grind. Comparing your beginning to someone else\'s middle undermines motivation and distorts realistic expectations.',
  },
  {
    id: 'motivation-rest-guilt',
    category: 'motivation',
    icon: '🛌',
    headline: 'Rest day guilt is counterproductive',
    body: 'Feeling guilty about rest increases cortisol and reduces recovery quality. Reframing rest days as essential training components—not laziness—improves both results and mental health.',
  },

  // ── Performance (14) ───────────────────────────────────────
  {
    id: 'performance-power-output',
    category: 'performance',
    icon: '💨',
    headline: 'Power output declines with fatigue',
    body: 'Bar speed is a reliable indicator of neuromuscular fatigue within a session. Monitoring velocity helps you stop a set before technical breakdown reduces training quality.',
  },
  {
    id: 'performance-vbt',
    category: 'performance',
    icon: '📡',
    headline: 'Velocity-based training auto-regulates load',
    body: 'Tracking bar speed allows real-time load adjustments based on daily readiness. When velocity drops below a threshold, the set ends—preserving quality over ego lifting.',
  },
  {
    id: 'performance-neuromuscular',
    category: 'performance',
    icon: '⚡',
    headline: 'Neuromuscular efficiency improves with practice',
    body: 'Beginners gain strength rapidly through motor learning before significant muscle growth occurs. Improved coordination and firing patterns account for early strength gains.',
  },
  {
    id: 'performance-rfd',
    category: 'performance',
    icon: '🚀',
    headline: 'Rate of force development matters for athletes',
    body: 'How quickly you can produce maximal force determines explosive performance. Olympic lifts and plyometrics train the stretch-shortening cycle for faster force application.',
  },
  {
    id: 'performance-plyometrics',
    category: 'performance',
    icon: '🦘',
    headline: 'Plyometrics train the stretch-shortening cycle',
    body: 'Explosive jumps and bounds improve the elastic energy storage in tendons and muscles. Low-volume plyometric work before strength sessions can enhance power output.',
  },
  {
    id: 'performance-grip-deadlift',
    category: 'performance',
    icon: '✊',
    headline: 'Mixed grip and hook grip save deadlifts',
    body: 'Grip failure limits deadlift progress long before the posterior chain fatigues. Mixed grip, hook grip, or strategic strap use on volume sets keeps loads progressing.',
  },
  {
    id: 'performance-bracing',
    category: 'performance',
    icon: '🫁',
    headline: 'Proper bracing transfers force efficiently',
    body: 'The Valsalva maneuver—inhaled breath held against a braced core—increases intra-abdominal pressure. This stabilizes the spine and allows heavier, safer compound lifts.',
  },
  {
    id: 'performance-squat-stance',
    category: 'performance',
    icon: '🦶',
    headline: 'Squat stance should match your anatomy',
    body: 'Hip structure and femur length determine ideal foot placement and depth. Experimenting with stance width and toe angle finds the position that allows deepest, strongest squats.',
  },
  {
    id: 'performance-bar-path',
    category: 'performance',
    icon: '📏',
    headline: 'Bar path efficiency saves energy',
    body: 'A vertical bar path over mid-foot minimizes moment arms and wasted effort. Filming lifts from the side reveals deviations that limit load and increase injury risk.',
  },
  {
    id: 'performance-intra-set-rest',
    category: 'performance',
    icon: '⏳',
    headline: 'Intra-set rest extends set quality',
    body: 'Pausing 10–20 seconds between reps in a heavy set partially restores phosphocreatine. This rest-pause technique allows more quality reps at a given load.',
  },
  {
    id: 'performance-pap',
    category: 'performance',
    icon: '🔋',
    headline: 'Post-activation potentiation boosts power',
    body: 'A heavy set performed before an explosive movement temporarily enhances neuromuscular output. A heavy squat before a vertical jump can increase jump height for 3–8 minutes.',
  },
  {
    id: 'performance-cns-fatigue',
    category: 'performance',
    icon: '🧠',
    headline: 'CNS fatigue limits heavy training frequency',
    body: 'Maximal effort lifts tax the central nervous system more than muscles. Programming heavy days with adequate spacing prevents CNS fatigue from masking true strength levels.',
  },
  {
    id: 'performance-rate-coding',
    category: 'performance',
    icon: '🔢',
    headline: 'Motor unit recruitment drives maximal strength',
    body: 'High-threshold motor units fire only during near-maximal efforts. Training above 85% of one-rep max improves the nervous system\'s ability to recruit these fibers.',
  },
  {
    id: 'performance-peak-force',
    category: 'performance',
    icon: '🏔️',
    headline: 'Peak force varies across the day',
    body: 'Circadian rhythms affect core temperature and neuromuscular output. Most people produce peak force in the late afternoon, though consistent training time matters more than timing optimization.',
  },

  // ── Coaching (14) ──────────────────────────────────────────
  {
    id: 'coaching-form-feedback',
    category: 'coaching',
    icon: '📹',
    headline: 'AI form analysis catches what you miss',
    body: 'Video-based movement analysis identifies compensations invisible in real time. Correcting form early prevents injury patterns from becoming ingrained habits.',
  },
  {
    id: 'coaching-auto-regulation',
    category: 'coaching',
    icon: '🤖',
    headline: 'Smart coaching adapts to your readiness',
    body: 'AI coaching systems adjust prescribed loads based on recent performance trends and reported fatigue. This auto-regulation prevents overreaching during accumulated stress.',
  },
  {
    id: 'coaching-personalized-volume',
    category: 'coaching',
    icon: '📐',
    headline: 'Personalized volume beats generic programs',
    body: 'Optimal training volume varies by individual recovery capacity and training age. Adaptive coaching increases or decreases sets based on your response, not a fixed template.',
  },
  {
    id: 'coaching-exercise-substitution',
    category: 'coaching',
    icon: '🔀',
    headline: 'Smart substitutions keep training on track',
    body: 'When equipment or pain limits an exercise, effective substitutions maintain the intended muscle stimulus. Coaching AI suggests alternatives that preserve program intent.',
  },
  {
    id: 'coaching-progressive-suggestions',
    category: 'coaching',
    icon: '⬆️',
    headline: 'Progressive overload suggestions remove guesswork',
    body: 'Data-driven load recommendations based on your rep performance eliminate arbitrary weight jumps. Small, calculated increases keep you progressing without unnecessary plateaus.',
  },
  {
    id: 'coaching-rest-recommendations',
    category: 'coaching',
    icon: '🛌',
    headline: 'Coaching flags when you need rest',
    body: 'Declining performance across multiple sessions signals insufficient recovery. Intelligent coaching recommends deloads or rest days before overreaching becomes overtraining.',
  },
  {
    id: 'coaching-nutrition-timing',
    category: 'coaching',
    icon: '🍽️',
    headline: 'Coaching connects training to nutrition',
    body: 'Hard training days warrant higher carbohydrate intake; rest days need less. Integrated coaching aligns your nutrition suggestions with your actual training load.',
  },
  {
    id: 'coaching-weak-points',
    category: 'coaching',
    icon: '🔍',
    headline: 'Weak point analysis targets lagging areas',
    body: 'Identifying muscles or movement phases that limit compound lift performance focuses accessory work effectively. Targeted coaching accelerates progress on stubborn lifts.',
  },
  {
    id: 'coaching-adherence',
    category: 'coaching',
    icon: '📅',
    headline: 'Adherence tracking keeps you honest',
    body: 'The best program is the one you actually follow. Coaching systems that track completion rates and flag missed sessions help maintain the consistency that drives results.',
  },
  {
    id: 'coaching-real-time-adjustments',
    category: 'coaching',
    icon: '⚡',
    headline: 'Real-time adjustments mid-workout help',
    body: 'If you fail an early set, coaching can reduce remaining volume to match your current capacity. Mid-session adjustments prevent junk volume and protect recovery.',
  },
  {
    id: 'coaching-periodization',
    category: 'coaching',
    icon: '📊',
    headline: 'Long-term periodization prevents stagnation',
    body: 'AI coaching cycles through hypertrophy, strength, and peaking phases based on your goals and competition dates. Structured periodization ensures continuous adaptation over months.',
  },
  {
    id: 'coaching-injury-risk',
    category: 'coaching',
    icon: '🩹',
    headline: 'Injury risk flags protect longevity',
    body: 'Sudden load spikes and asymmetric fatigue patterns increase injury probability. Coaching systems that monitor training load trends can flag risky patterns before pain develops.',
  },
  {
    id: 'coaching-recovery-scoring',
    category: 'coaching',
    icon: '💚',
    headline: 'Recovery scores guide daily training decisions',
    body: 'Combining sleep, soreness, and performance data into a readiness score helps you train hard on green days and pull back on red ones. Data-driven recovery beats guessing.',
  },
  {
    id: 'coaching-goal-alignment',
    category: 'coaching',
    icon: '🎯',
    headline: 'Goal-aligned coaching keeps programs focused',
    body: 'Every exercise and set should serve your stated goal—strength, hypertrophy, or endurance. Coaching that audits program alignment prevents wasted effort on irrelevant training.',
  },
];
