import type { BodyArea, ExerciseCardData } from '@/types/exerciseCard';

/**
 * EXERCISE_DATABASE — the source of truth for Exercise Cards.
 *
 * Authored entries carry specific coaching cues, common mistakes, "what you
 * should feel", alternatives and equipment-independent replacements. Every
 * entry maps to a movement archetype so the animated anatomy figure works
 * without bespoke animation per exercise — this is what lets the catalog scale
 * from the curated set here toward 500+ exercises.
 *
 * Exercises not yet authored here are resolved at runtime from the Supabase
 * `exercises` table via `deriveCardFromExercise`, so the card screen always
 * renders something coherent while content is filled in.
 */
export const EXERCISE_DATABASE: Record<string, ExerciseCardData> = {
  // ───────────────────────── BACK / LATS ─────────────────────────
  'pull-up': {
    slug: 'pull-up',
    name: 'Pull-Up',
    category: 'pull',
    bodyArea: 'Lats',
    equipment: 'Pull-Up Bar',
    difficulty: 'Intermediate',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'mid-back', 'rear-delts'],
    archetype: 'vertical-pull',
    coachingCues: [
      'Pull elbows down toward your ribs',
      'Drive your chest toward the bar',
      'Pause briefly at the top',
      'Lower under control to full extension',
      'Keep your core tight, no swinging',
    ],
    commonMistakes: ['Swinging', 'Half reps', 'Shrugging shoulders', 'Kicking legs', 'Using momentum'],
    feel: {
      primary: ['lats'],
      secondary: ['biceps', 'mid-back', 'rear-delts'],
    },
    alternatives: ['chin-up', 'neutral-grip-pull-up', 'assisted-pull-up', 'wide-grip-pull-up', 'lat-pulldown'],
    replacements: ['inverted-row', 'band-pulldown', 'dumbbell-row'],
    requiresEquipment: ['pull-up-bar'],
    metric: 'reps',
    defaultRepGoal: 15,
    authored: true,
  },
  'chin-up': {
    slug: 'chin-up',
    name: 'Chin-Up',
    category: 'pull',
    bodyArea: 'Lats',
    equipment: 'Pull-Up Bar',
    difficulty: 'Intermediate',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['mid-back', 'forearms'],
    archetype: 'vertical-pull',
    coachingCues: [
      'Grip shoulder-width, palms facing you',
      'Lead with the chest, not the chin',
      'Squeeze biceps and lats at the top',
      'Control the descent for 2 seconds',
      'Keep ribs down to avoid arching',
    ],
    commonMistakes: ['Chin-craning over the bar', 'Partial lockout', 'Bouncing at the bottom', 'Elbows flaring wide', 'Rushing reps'],
    feel: { primary: ['lats', 'biceps'], secondary: ['mid-back', 'forearms'] },
    alternatives: ['pull-up', 'neutral-grip-pull-up', 'assisted-pull-up', 'lat-pulldown'],
    replacements: ['inverted-row', 'band-pulldown', 'dumbbell-row'],
    requiresEquipment: ['pull-up-bar'],
    metric: 'reps',
    defaultRepGoal: 12,
    authored: true,
  },
  'lat-pulldown': {
    slug: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'pull',
    bodyArea: 'Lats',
    equipment: 'Cable Machine',
    difficulty: 'Beginner',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'mid-back', 'rear-delts'],
    archetype: 'vertical-pull',
    coachingCues: [
      'Set thighs snug under the pad',
      'Pull the bar to your upper chest',
      'Drive elbows down and back',
      'Lean back only ~15 degrees',
      'Stretch tall at the top each rep',
    ],
    commonMistakes: ['Pulling behind the neck', 'Leaning back too far', 'Yanking with momentum', 'Stopping short of the chest', 'Wrists curling under'],
    feel: { primary: ['lats'], secondary: ['biceps', 'mid-back'] },
    alternatives: ['pull-up', 'chin-up', 'assisted-pull-up', 'straight-arm-pulldown'],
    replacements: ['band-pulldown', 'dumbbell-row', 'inverted-row'],
    requiresEquipment: ['cable', 'machine'],
    metric: 'reps_weight',
    authored: true,
  },
  'barbell-row': {
    slug: 'barbell-row',
    name: 'Barbell Row',
    category: 'pull',
    bodyArea: 'Mid Back',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    primaryMuscles: ['mid-back', 'lats'],
    secondaryMuscles: ['rear-delts', 'biceps', 'lower-back'],
    archetype: 'horizontal-pull',
    coachingCues: [
      'Hinge to ~45 degrees, flat back',
      'Pull the bar to your lower ribs',
      'Squeeze shoulder blades together',
      'Keep elbows tucked at ~45 degrees',
      'Lower the bar without rounding',
    ],
    commonMistakes: ['Standing up with the weight', 'Rounding the lower back', 'Jerking the bar', 'Shrugging instead of rowing', 'Half range of motion'],
    feel: { primary: ['mid-back', 'lats'], secondary: ['rear-delts', 'biceps'] },
    alternatives: ['dumbbell-row', 'seated-cable-row', 't-bar-row', 'pendlay-row'],
    replacements: ['inverted-row', 'band-row', 'dumbbell-row'],
    requiresEquipment: ['barbell'],
    metric: 'reps_weight',
    authored: true,
  },
  'dumbbell-row': {
    slug: 'dumbbell-row',
    name: 'Single Arm Dumbbell Row',
    category: 'pull',
    bodyArea: 'Mid Back',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    primaryMuscles: ['lats', 'mid-back'],
    secondaryMuscles: ['biceps', 'rear-delts'],
    archetype: 'horizontal-pull',
    coachingCues: [
      'Brace one hand on the bench',
      'Row the dumbbell to your hip',
      'Drive the elbow past your torso',
      'Keep hips square to the floor',
      'Lower until the lat fully stretches',
    ],
    commonMistakes: ['Twisting the torso to lift', 'Rowing to the armpit', 'Using a flexed lower back', 'Cutting the stretch short', 'Momentum from the legs'],
    feel: { primary: ['lats'], secondary: ['mid-back', 'biceps'] },
    alternatives: ['seated-cable-row', 'barbell-row', 'chest-supported-row'],
    replacements: ['inverted-row', 'band-row'],
    requiresEquipment: ['dumbbells'],
    metric: 'reps_weight',
    authored: true,
  },
  'seated-cable-row': {
    slug: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'pull',
    bodyArea: 'Mid Back',
    equipment: 'Cable Machine',
    difficulty: 'Beginner',
    primaryMuscles: ['mid-back', 'lats'],
    secondaryMuscles: ['biceps', 'rear-delts'],
    archetype: 'horizontal-pull',
    coachingCues: [
      'Sit tall with a slight forward lean to start',
      'Pull the handle to your belly button',
      'Lead with the elbows, not the hands',
      'Squeeze the shoulder blades 1 second',
      'Let the weight stretch you forward, no rounding',
    ],
    commonMistakes: ['Heaving with the lower back', 'Shrugging at the top', 'Short, choppy reps', 'Rounding to reach forward', 'Using too much arm'],
    feel: { primary: ['mid-back'], secondary: ['lats', 'biceps'] },
    alternatives: ['dumbbell-row', 'barbell-row', 'chest-supported-row'],
    replacements: ['band-row', 'inverted-row', 'dumbbell-row'],
    requiresEquipment: ['cable', 'machine'],
    metric: 'reps_weight',
    authored: true,
  },
  'face-pull': {
    slug: 'face-pull',
    name: 'Face Pull',
    category: 'pull',
    bodyArea: 'Rear Delts',
    equipment: 'Cable Machine',
    difficulty: 'Beginner',
    primaryMuscles: ['rear-delts'],
    secondaryMuscles: ['traps', 'mid-back'],
    archetype: 'horizontal-pull',
    coachingCues: [
      'Set the cable at face height',
      'Pull the rope toward your eyes',
      'Externally rotate — knuckles to the ceiling',
      'Lead with the elbows high',
      'Pause and squeeze the rear delts',
    ],
    commonMistakes: ['Pulling too low to the chest', 'Using the lower back', 'No external rotation', 'Going too heavy', 'Shrugging the traps'],
    feel: { primary: ['rear-delts'], secondary: ['traps', 'mid-back'] },
    alternatives: ['reverse-pec-deck', 'rear-delt-fly', 'band-pull-apart'],
    replacements: ['band-pull-apart', 'rear-delt-fly'],
    requiresEquipment: ['cable'],
    metric: 'reps_weight',
    authored: true,
  },
  'deadlift': {
    slug: 'deadlift',
    name: 'Deadlift',
    category: 'hinge',
    bodyArea: 'Hamstrings',
    equipment: 'Barbell',
    difficulty: 'Advanced',
    primaryMuscles: ['glutes', 'hamstrings', 'lower-back'],
    secondaryMuscles: ['lats', 'traps', 'forearms', 'quads'],
    archetype: 'hinge',
    coachingCues: [
      'Bar over mid-foot, shins close',
      'Take the slack out before you pull',
      'Push the floor away with your legs',
      'Drive hips and chest up together',
      'Lock out by squeezing the glutes',
    ],
    commonMistakes: ['Rounding the lower back', 'Hips shooting up first', 'Bar drifting away from shins', 'Hyperextending at lockout', 'Jerking off the floor'],
    feel: { primary: ['glutes', 'hamstrings'], secondary: ['lower-back', 'traps'] },
    alternatives: ['romanian-deadlift', 'trap-bar-deadlift', 'sumo-deadlift', 'rack-pull'],
    replacements: ['romanian-deadlift', 'dumbbell-romanian-deadlift', 'hip-thrust', 'kettlebell-swing'],
    requiresEquipment: ['barbell'],
    metric: 'reps_weight',
    authored: true,
  },
  'romanian-deadlift': {
    slug: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'hinge',
    bodyArea: 'Hamstrings',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower-back', 'forearms'],
    archetype: 'hinge',
    coachingCues: [
      'Start standing, soft knees',
      'Push hips back, bar against the thighs',
      'Lower until you feel the hamstrings stretch',
      'Keep the back flat the whole way',
      'Drive hips forward to stand tall',
    ],
    commonMistakes: ['Squatting instead of hinging', 'Rounding the back', 'Bar drifting forward', 'Overextending at the top', 'Going below the stretch by bending the back'],
    feel: { primary: ['hamstrings'], secondary: ['glutes', 'lower-back'] },
    alternatives: ['deadlift', 'dumbbell-romanian-deadlift', 'good-morning', 'leg-curl'],
    replacements: ['dumbbell-romanian-deadlift', 'leg-curl', 'kettlebell-swing', 'glute-ham-raise'],
    requiresEquipment: ['barbell'],
    metric: 'reps_weight',
    authored: true,
  },
  'hip-thrust': {
    slug: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'hinge',
    bodyArea: 'Glutes',
    equipment: 'Barbell',
    difficulty: 'Beginner',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quads'],
    archetype: 'hinge',
    coachingCues: [
      'Upper back on the bench, ribs down',
      'Tuck the chin, eyes forward',
      'Drive through the heels',
      'Squeeze glutes hard at the top',
      'Stop at a flat torso, no overarching',
    ],
    commonMistakes: ['Arching the lower back', 'Pushing through the toes', 'Half lockout', 'Neck craning back', 'Feet too far forward'],
    feel: { primary: ['glutes'], secondary: ['hamstrings'] },
    alternatives: ['glute-bridge', 'romanian-deadlift', 'cable-pull-through'],
    replacements: ['glute-bridge', 'dumbbell-hip-thrust', 'cable-pull-through'],
    requiresEquipment: ['barbell', 'bench'],
    metric: 'reps_weight',
    authored: true,
  },

  // ───────────────────────── CHEST ─────────────────────────
  'bench-press': {
    slug: 'bench-press',
    name: 'Bench Press',
    category: 'push',
    bodyArea: 'Chest',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    archetype: 'horizontal-press',
    coachingCues: [
      'Pin shoulder blades down and back',
      'Lower the bar to your lower chest',
      'Keep elbows at ~75 degrees, not flared',
      'Drive your feet into the floor',
      'Press up and slightly back over the shoulders',
    ],
    commonMistakes: ['Bouncing off the chest', 'Flaring elbows to 90 degrees', 'Lifting hips off the bench', 'Half lockout', 'Uneven bar path'],
    feel: { primary: ['chest'], secondary: ['triceps', 'front-delts'] },
    alternatives: ['incline-bench-press', 'dumbbell-bench-press', 'machine-chest-press', 'close-grip-bench-press'],
    replacements: ['push-up', 'dumbbell-bench-press', 'band-chest-press', 'dips'],
    requiresEquipment: ['barbell', 'bench'],
    metric: 'reps_weight',
    authored: true,
  },
  'incline-bench-press': {
    slug: 'incline-bench-press',
    name: 'Incline Bench Press',
    category: 'push',
    bodyArea: 'Chest',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    primaryMuscles: ['chest', 'front-delts'],
    secondaryMuscles: ['triceps'],
    archetype: 'horizontal-press',
    coachingCues: [
      'Set the bench to 30 degrees, not higher',
      'Lower the bar to your upper chest',
      'Keep wrists stacked over elbows',
      'Tuck elbows slightly on the descent',
      'Press without letting the shoulders roll forward',
    ],
    commonMistakes: ['Bench angle too steep', 'Bar drifting to the neck', 'Elbows flaring', 'Shoulders shrugging up', 'Partial reps'],
    feel: { primary: ['chest', 'front-delts'], secondary: ['triceps'] },
    alternatives: ['bench-press', 'incline-dumbbell-press', 'machine-chest-press'],
    replacements: ['push-up', 'incline-dumbbell-press', 'band-chest-press'],
    requiresEquipment: ['barbell', 'bench'],
    metric: 'reps_weight',
    authored: true,
  },
  'dumbbell-bench-press': {
    slug: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'push',
    bodyArea: 'Chest',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front-delts'],
    archetype: 'horizontal-press',
    coachingCues: [
      'Start with dumbbells over the shoulders',
      'Lower until the elbows reach chest depth',
      'Keep a slight arch in the upper back',
      'Press the dumbbells together at the top',
      'Control the eccentric — no dropping',
    ],
    commonMistakes: ['Clanging the dumbbells together hard', 'Elbows flaring wide', 'Pressing unevenly', 'Cutting depth short', 'Wrists bending back'],
    feel: { primary: ['chest'], secondary: ['triceps', 'front-delts'] },
    alternatives: ['bench-press', 'incline-dumbbell-press', 'machine-chest-press', 'push-up'],
    replacements: ['push-up', 'band-chest-press', 'dips'],
    requiresEquipment: ['dumbbells', 'bench'],
    metric: 'reps_weight',
    authored: true,
  },
  'push-up': {
    slug: 'push-up',
    name: 'Push-Up',
    category: 'push',
    bodyArea: 'Chest',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front-delts', 'core'],
    archetype: 'horizontal-press',
    coachingCues: [
      'Hands just outside the shoulders',
      'Brace the core into one straight line',
      'Lower the chest to a fist off the floor',
      'Keep elbows at ~45 degrees',
      'Press the floor away and lock out',
    ],
    commonMistakes: ['Sagging hips', 'Flaring elbows to 90 degrees', 'Half depth', 'Head dropping forward', 'Hips piking up'],
    feel: { primary: ['chest'], secondary: ['triceps', 'core'] },
    alternatives: ['dumbbell-bench-press', 'bench-press', 'dips', 'incline-push-up'],
    replacements: ['band-chest-press', 'machine-chest-press'],
    requiresEquipment: ['bodyweight'],
    metric: 'reps',
    defaultRepGoal: 30,
    authored: true,
  },
  'dips': {
    slug: 'dips',
    name: 'Dips',
    category: 'push',
    bodyArea: 'Triceps',
    equipment: 'Dip Station',
    difficulty: 'Intermediate',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['front-delts'],
    archetype: 'vertical-press',
    coachingCues: [
      'Start at a strong, locked-out top',
      'Lower until the upper arms are parallel',
      'Lean forward slightly for more chest',
      'Stay vertical for more triceps',
      'Press up without bouncing at the bottom',
    ],
    commonMistakes: ['Going too deep and stressing the shoulders', 'Half reps', 'Swinging the legs', 'Shrugging at the bottom', 'Flaring elbows wide'],
    feel: { primary: ['triceps', 'chest'], secondary: ['front-delts'] },
    alternatives: ['close-grip-bench-press', 'bench-dip', 'machine-dip'],
    replacements: ['bench-dip', 'push-up', 'triceps-pushdown'],
    requiresEquipment: ['dip-station'],
    metric: 'reps',
    defaultRepGoal: 15,
    authored: true,
  },

  // ───────────────────────── SHOULDERS ─────────────────────────
  'overhead-press': {
    slug: 'overhead-press',
    name: 'Overhead Press',
    category: 'push',
    bodyArea: 'Shoulders',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    primaryMuscles: ['front-delts', 'side-delts'],
    secondaryMuscles: ['triceps', 'traps', 'core'],
    archetype: 'vertical-press',
    coachingCues: [
      'Grip just outside the shoulders',
      'Squeeze glutes and brace the core',
      'Press the bar in a straight line',
      'Move your head back, then through the bar',
      'Lock out with the bar over mid-foot',
    ],
    commonMistakes: ['Leaning back excessively', 'Pressing around the face', 'Soft, unbraced core', 'Half lockout', 'Heaving with the legs'],
    feel: { primary: ['front-delts', 'side-delts'], secondary: ['triceps'] },
    alternatives: ['dumbbell-shoulder-press', 'machine-shoulder-press', 'push-press', 'arnold-press'],
    replacements: ['dumbbell-shoulder-press', 'band-overhead-press', 'pike-push-up'],
    requiresEquipment: ['barbell'],
    metric: 'reps_weight',
    authored: true,
  },
  'dumbbell-shoulder-press': {
    slug: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'push',
    bodyArea: 'Shoulders',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    primaryMuscles: ['front-delts', 'side-delts'],
    secondaryMuscles: ['triceps'],
    archetype: 'vertical-press',
    coachingCues: [
      'Start with dumbbells at ear height',
      'Keep wrists stacked over elbows',
      'Press up and slightly inward',
      'Avoid clashing the dumbbells at the top',
      'Lower under control to the start',
    ],
    commonMistakes: ['Arching the lower back', 'Pressing too far forward', 'Half range of motion', 'Wrists bending back', 'Using leg drive'],
    feel: { primary: ['front-delts', 'side-delts'], secondary: ['triceps'] },
    alternatives: ['overhead-press', 'arnold-press', 'machine-shoulder-press'],
    replacements: ['band-overhead-press', 'pike-push-up'],
    requiresEquipment: ['dumbbells'],
    metric: 'reps_weight',
    authored: true,
  },
  'lateral-raise': {
    slug: 'lateral-raise',
    name: 'Lateral Raise',
    category: 'push',
    bodyArea: 'Shoulders',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    primaryMuscles: ['side-delts'],
    secondaryMuscles: ['traps'],
    archetype: 'lateral-raise',
    coachingCues: [
      'Soft bend in the elbows, lock the angle',
      'Lead with the elbows, not the hands',
      'Raise to shoulder height, no higher',
      'Tilt pinkies slightly up at the top',
      'Lower slowly for a 2-count',
    ],
    commonMistakes: ['Swinging with momentum', 'Shrugging the traps', 'Going above shoulder height', 'Bending elbows mid-rep', 'Leaning back to cheat'],
    feel: { primary: ['side-delts'], secondary: ['traps'] },
    alternatives: ['cable-lateral-raise', 'machine-lateral-raise', 'upright-row'],
    replacements: ['band-lateral-raise', 'cable-lateral-raise'],
    requiresEquipment: ['dumbbells'],
    metric: 'reps_weight',
    authored: true,
  },

  // ───────────────────────── ARMS ─────────────────────────
  'barbell-curl': {
    slug: 'barbell-curl',
    name: 'Barbell Curl',
    category: 'pull',
    bodyArea: 'Biceps',
    equipment: 'Barbell',
    difficulty: 'Beginner',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    archetype: 'curl',
    coachingCues: [
      'Pin the elbows to your sides',
      'Curl by flexing the biceps, not swinging',
      'Keep the wrists neutral',
      'Squeeze hard at the top',
      'Lower for a full 2-count stretch',
    ],
    commonMistakes: ['Swinging the torso', 'Elbows drifting forward', 'Half reps', 'Wrists curling under', 'Using too much weight'],
    feel: { primary: ['biceps'], secondary: ['forearms'] },
    alternatives: ['dumbbell-curl', 'ez-bar-curl', 'cable-curl', 'preacher-curl'],
    replacements: ['dumbbell-curl', 'band-curl', 'chin-up'],
    requiresEquipment: ['barbell'],
    metric: 'reps_weight',
    authored: true,
  },
  'dumbbell-curl': {
    slug: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    category: 'pull',
    bodyArea: 'Biceps',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    archetype: 'curl',
    coachingCues: [
      'Start with arms fully extended',
      'Keep elbows fixed at your sides',
      'Supinate — rotate pinky up as you curl',
      'Squeeze the biceps at the top',
      'Lower slowly, resist the negative',
    ],
    commonMistakes: ['Swinging the dumbbells up', 'Elbows flaring out', 'Partial range', 'Shrugging the shoulders', 'Dropping the weight on the way down'],
    feel: { primary: ['biceps'], secondary: ['forearms'] },
    alternatives: ['barbell-curl', 'hammer-curl', 'cable-curl', 'preacher-curl'],
    replacements: ['band-curl', 'chin-up'],
    requiresEquipment: ['dumbbells'],
    metric: 'reps_weight',
    authored: true,
  },
  'triceps-pushdown': {
    slug: 'triceps-pushdown',
    name: 'Triceps Pushdown',
    category: 'push',
    bodyArea: 'Triceps',
    equipment: 'Cable Machine',
    difficulty: 'Beginner',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
    archetype: 'triceps-extension',
    coachingCues: [
      'Pin the elbows to your ribs',
      'Push down until the arms lock out',
      'Squeeze the triceps at the bottom',
      'Let the forearms rise only to ~90 degrees',
      'Keep a slight forward lean, core braced',
    ],
    commonMistakes: ['Elbows flaring out', 'Leaning over to use bodyweight', 'Short reps that never lock out', 'Shrugging at the top', 'Wrists breaking under load'],
    feel: { primary: ['triceps'], secondary: ['forearms'] },
    alternatives: ['overhead-triceps-extension', 'skull-crusher', 'close-grip-bench-press', 'dips'],
    replacements: ['band-pushdown', 'bench-dip', 'close-grip-push-up'],
    requiresEquipment: ['cable'],
    metric: 'reps_weight',
    authored: true,
  },

  // ───────────────────────── LEGS ─────────────────────────
  'squat': {
    slug: 'squat',
    name: 'Squat',
    category: 'squat',
    bodyArea: 'Quads',
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core', 'lower-back'],
    archetype: 'squat',
    coachingCues: [
      'Brace your core before you descend',
      'Break at the hips and knees together',
      'Push your knees out over your toes',
      'Sit to at least parallel depth',
      'Drive through mid-foot to stand',
    ],
    commonMistakes: ['Knees caving inward', 'Heels lifting off the floor', 'Rounding the lower back', 'Cutting depth short', 'Good-morning-ing the weight up'],
    feel: { primary: ['quads', 'glutes'], secondary: ['hamstrings', 'core'] },
    alternatives: ['front-squat', 'goblet-squat', 'leg-press', 'hack-squat', 'bulgarian-split-squat'],
    replacements: ['goblet-squat', 'leg-press', 'bulgarian-split-squat', 'walking-lunge'],
    requiresEquipment: ['barbell', 'rack'],
    metric: 'reps_weight',
    authored: true,
  },
  'front-squat': {
    slug: 'front-squat',
    name: 'Front Squat',
    category: 'squat',
    bodyArea: 'Quads',
    equipment: 'Barbell',
    difficulty: 'Advanced',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'core', 'upper-back'],
    archetype: 'squat',
    coachingCues: [
      'Rest the bar on the front delts, elbows high',
      'Keep the torso as upright as possible',
      'Brace hard — the core holds position',
      'Descend straight down, knees forward',
      'Drive up keeping the elbows pointed ahead',
    ],
    commonMistakes: ['Elbows dropping forward', 'Rounding the upper back', 'Heels rising', 'Shifting weight to the toes', 'Losing depth to stay upright'],
    feel: { primary: ['quads'], secondary: ['glutes', 'core'] },
    alternatives: ['squat', 'goblet-squat', 'hack-squat', 'leg-press'],
    replacements: ['goblet-squat', 'leg-press', 'bulgarian-split-squat'],
    requiresEquipment: ['barbell', 'rack'],
    metric: 'reps_weight',
    authored: true,
  },
  'leg-press': {
    slug: 'leg-press',
    name: 'Leg Press',
    category: 'squat',
    bodyArea: 'Quads',
    equipment: 'Machine',
    difficulty: 'Beginner',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    archetype: 'squat',
    coachingCues: [
      'Feet shoulder-width, mid-platform',
      'Lower until the knees reach ~90 degrees',
      'Keep the lower back flat on the pad',
      'Push through the whole foot',
      'Stop just short of locking the knees',
    ],
    commonMistakes: ['Lower back rounding off the pad', 'Bouncing at the bottom', 'Locking knees hard at the top', 'Half range of motion', 'Knees caving in'],
    feel: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
    alternatives: ['squat', 'hack-squat', 'goblet-squat', 'leg-extension'],
    replacements: ['goblet-squat', 'bulgarian-split-squat', 'walking-lunge'],
    requiresEquipment: ['machine'],
    metric: 'reps_weight',
    authored: true,
  },
  'leg-extension': {
    slug: 'leg-extension',
    name: 'Leg Extension',
    category: 'squat',
    bodyArea: 'Quads',
    equipment: 'Machine',
    difficulty: 'Beginner',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    archetype: 'static',
    coachingCues: [
      'Align the knees with the pivot point',
      'Pad sits on the lower shin',
      'Extend until the legs are straight',
      'Squeeze the quads hard for 1 second',
      'Lower slowly, resist the negative',
    ],
    commonMistakes: ['Swinging the weight up', 'Half reps', 'Slamming the stack down', 'Hips lifting off the seat', 'Going too heavy and using momentum'],
    feel: { primary: ['quads'], secondary: [] },
    alternatives: ['leg-press', 'squat', 'goblet-squat'],
    replacements: ['bulgarian-split-squat', 'goblet-squat', 'wall-sit'],
    requiresEquipment: ['machine'],
    metric: 'reps_weight',
    authored: true,
  },
  'leg-curl': {
    slug: 'leg-curl',
    name: 'Leg Curl',
    category: 'hinge',
    bodyArea: 'Hamstrings',
    equipment: 'Machine',
    difficulty: 'Beginner',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    archetype: 'static',
    coachingCues: [
      'Align the knees with the machine pivot',
      'Curl the pad toward your glutes',
      'Keep the hips pressed into the bench',
      'Squeeze the hamstrings at the top',
      'Lower under control, no dropping',
    ],
    commonMistakes: ['Hips lifting off the pad', 'Partial range of motion', 'Jerking the weight', 'Letting the weight drop fast', 'Pointing the toes incorrectly for the variation'],
    feel: { primary: ['hamstrings'], secondary: ['calves'] },
    alternatives: ['romanian-deadlift', 'glute-ham-raise', 'nordic-curl'],
    replacements: ['nordic-curl', 'romanian-deadlift', 'glute-ham-raise'],
    requiresEquipment: ['machine'],
    metric: 'reps_weight',
    authored: true,
  },
  'walking-lunge': {
    slug: 'walking-lunge',
    name: 'Walking Lunge',
    category: 'squat',
    bodyArea: 'Quads',
    equipment: 'Dumbbell',
    difficulty: 'Beginner',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    archetype: 'lunge',
    coachingCues: [
      'Step out to a comfortable stride length',
      'Drop the back knee toward the floor',
      'Keep the front shin near vertical',
      'Push through the front heel to rise',
      'Stay tall — no forward torso collapse',
    ],
    commonMistakes: ['Short steps cramping the knee', 'Front knee caving in', 'Leaning too far forward', 'Pushing off the back toe', 'Losing balance from rushing'],
    feel: { primary: ['quads', 'glutes'], secondary: ['hamstrings'] },
    alternatives: ['bulgarian-split-squat', 'reverse-lunge', 'split-squat', 'leg-press'],
    replacements: ['bodyweight-lunge', 'bulgarian-split-squat', 'step-up'],
    requiresEquipment: ['dumbbells'],
    metric: 'reps_weight',
    authored: true,
  },
  'standing-calf-raise': {
    slug: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'push',
    bodyArea: 'Calves',
    equipment: 'Machine',
    difficulty: 'Beginner',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    archetype: 'calf-raise',
    coachingCues: [
      'Balls of the feet on the platform',
      'Drop the heels for a full stretch',
      'Drive up onto the toes as high as possible',
      'Pause and squeeze at the top',
      'Lower slowly for a 2-count',
    ],
    commonMistakes: ['Bouncing through reps', 'Cutting the stretch short', 'Bending the knees to cheat', 'Short range at the top', 'Going too fast'],
    feel: { primary: ['calves'], secondary: [] },
    alternatives: ['seated-calf-raise', 'leg-press-calf-raise', 'donkey-calf-raise'],
    replacements: ['bodyweight-calf-raise', 'single-leg-calf-raise'],
    requiresEquipment: ['machine'],
    metric: 'reps_weight',
    authored: true,
  },

  // ───────────────────────── CORE ─────────────────────────
  'plank': {
    slug: 'plank',
    name: 'Plank',
    category: 'core',
    bodyArea: 'Core',
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    primaryMuscles: ['abs', 'core'],
    secondaryMuscles: ['obliques', 'lower-back'],
    archetype: 'static',
    coachingCues: [
      'Elbows under the shoulders',
      'Squeeze glutes and brace the abs',
      'Form one straight line head to heels',
      'Tuck the chin, eyes down',
      'Breathe steadily — don’t hold your breath',
    ],
    commonMistakes: ['Hips sagging', 'Hips piking up', 'Head dropping', 'Holding the breath', 'Shoulders creeping toward the ears'],
    feel: { primary: ['abs', 'core'], secondary: ['obliques'] },
    alternatives: ['hanging-leg-raise', 'ab-wheel-rollout', 'dead-bug'],
    replacements: ['dead-bug', 'hollow-hold'],
    requiresEquipment: ['bodyweight'],
    metric: 'time',
    authored: true,
  },
  'hanging-leg-raise': {
    slug: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'core',
    bodyArea: 'Core',
    equipment: 'Pull-Up Bar',
    difficulty: 'Intermediate',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip-flexors', 'obliques', 'forearms'],
    archetype: 'core-flexion',
    coachingCues: [
      'Hang with active shoulders, no shrugging',
      'Initiate by curling the pelvis up',
      'Raise the legs to at least parallel',
      'Avoid swinging — control the bottom',
      'Lower slowly with the abs engaged',
    ],
    commonMistakes: ['Swinging for momentum', 'Only using the hip flexors', 'Half range of motion', 'Dropping the legs fast', 'Bending the knees to cheat'],
    feel: { primary: ['abs'], secondary: ['hip-flexors', 'obliques'] },
    alternatives: ['captains-chair-leg-raise', 'lying-leg-raise', 'ab-wheel-rollout'],
    replacements: ['lying-leg-raise', 'reverse-crunch', 'dead-bug'],
    requiresEquipment: ['pull-up-bar'],
    metric: 'reps',
    defaultRepGoal: 15,
    authored: true,
  },
};

export const EXERCISE_SLUGS = Object.keys(EXERCISE_DATABASE);

export function getExerciseCard(slug: string): ExerciseCardData | undefined {
  return EXERCISE_DATABASE[slug];
}

function slugify(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function getExerciseCardByName(name: string): ExerciseCardData | undefined {
  const slug = slugify(name);
  if (EXERCISE_DATABASE[slug]) return EXERCISE_DATABASE[slug];
  const lower = name.trim().toLowerCase();
  return Object.values(EXERCISE_DATABASE).find((e) => e.name.toLowerCase() === lower);
}

/** Title-case a slug for display when the referenced exercise isn't authored. */
export function titleizeSlug(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export type ExerciseRef = {
  slug: string;
  name: string;
  bodyArea?: BodyArea;
  equipment?: string;
  /** True when a full authored card exists for this reference. */
  authored: boolean;
};

export function resolveExerciseRef(slug: string): ExerciseRef {
  const card = EXERCISE_DATABASE[slug];
  if (card) {
    return {
      slug,
      name: card.name,
      bodyArea: card.bodyArea,
      equipment: card.equipment,
      authored: true,
    };
  }
  return { slug, name: titleizeSlug(slug), authored: false };
}
