/** Native modules stripped from diagnostic TestFlight builds (B26 baseline). */
export const DIAGNOSTIC_B27_NATIVE_EXCLUDES = [
  '@kingstinct/react-native-healthkit',
  'react-native-nitro-modules',
  'react-native-purchases',
  'react-native-watch-connectivity',
  'expo-speech-recognition',
  'expo-dev-client',
  'expo-dev-launcher',
  'expo-dev-menu',
  'expo-dev-menu-interface',
  'react-native-reanimated',
  'react-native-worklets',
  '@sentry/react-native',
  'react-native-svg',
  'expo-updates',
  'expo-updates-interface',
  'react-native-gesture-handler',
  'react-native-screens',
  'react-native-safe-area-context',
  '@react-native-async-storage/async-storage',
  'expo-router',
  'expo-av',
  'expo-notifications',
  'expo-location',
  'expo-image',
  'expo-image-picker',
  'expo-linear-gradient',
  'expo-speech',
  'expo-secure-store',
  'expo-sharing',
  'expo-web-browser',
  'expo-system-ui',
  'expo-symbols',
  'expo-file-system',
  'expo-font',
  'expo-linking',
  'expo-device',
  'expo-eas-client',
  'expo-application',
  'expo-structured-headers',
  'expo-manifests',
  'expo-json-utils',
  'expo-image-loader',
] as const;

/** B28: B27 baseline + Expo Router navigation deps only. */
export const DIAGNOSTIC_B28_NATIVE_EXCLUDES = DIAGNOSTIC_B27_NATIVE_EXCLUDES.filter(
  (name) =>
    ![
      'expo-router',
      'react-native-screens',
      'react-native-safe-area-context',
      'react-native-gesture-handler',
      'expo-linking',
    ].includes(name),
);
