#!/usr/bin/env node
/**
 * Generate supabase/migrations/026_fix_exercise_metadata_from_names.sql
 * using the same inference engine as runtime exercise education.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

import { inferExerciseMetadata } from '../src/lib/exerciseEducation/inferExerciseMetadata.ts';
import { loadExerciseCatalog } from './lib/parse-exercise-catalog.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const outPath = path.join(root, 'supabase/migrations/026_fix_exercise_metadata_from_names.sql');

function esc(value: string): string {
  return value.replace(/'/g, "''");
}

function sqlArray(values: string[]): string {
  if (values.length === 0) return 'array[]::text[]';
  return `array[${values.map((v) => `'${esc(v)}'`).join(', ')}]`;
}

function requiresForEquipment(equipment: string, requires: string[]): string[] {
  if (requires.length) return requires;
  switch (equipment) {
    case 'dumbbell':
      return ['dumbbells'];
    case 'barbell':
      return ['barbell', 'rack'];
    case 'bodyweight':
      return ['bodyweight'];
    case 'cable':
    case 'machine':
    case 'rower':
      return ['machines'];
    case 'bands':
      return ['bands'];
    case 'kettlebell':
      return ['dumbbells'];
    default:
      return [equipment];
  }
}

function main() {
  const catalog = loadExerciseCatalog();
  const lines = [
    '-- Correct exercise catalog metadata using name-based inference (matches runtime education).',
    '-- Generated by scripts/generate-exercise-metadata-migration.ts — do not edit by hand.',
    '',
  ];

  let updated = 0;
  for (const row of catalog) {
    const inferred = inferExerciseMetadata({
      name: row.name,
      slug: row.slug,
      category: row.category,
      equipment: row.equipment,
      muscleGroups: row.muscleGroups ?? [row.muscle],
      exerciseType: row.exerciseType,
    });

    const requires = requiresForEquipment(inferred.equipment, inferred.requires);
    const metaPatch = {
      requires,
      movement_family: inferred.movementPattern,
      education_corrected_at: '2026-06-24',
      education_version: 1,
    };

    lines.push(
      `update public.exercises set category = '${esc(inferred.movementCategory)}'::movement_category, equipment = '${esc(inferred.equipment)}', muscle_groups = ${sqlArray(inferred.primaryMuscles)}, secondary_muscles = ${sqlArray(inferred.secondaryMuscles)}, exercise_type = '${esc(inferred.exerciseType)}'::exercise_type, metadata = coalesce(metadata, '{}'::jsonb) || '${esc(JSON.stringify(metaPatch))}'::jsonb, updated_at = now() where slug = '${esc(row.slug)}' and is_system = true;`,
    );
    updated += 1;
  }

  fs.writeFileSync(outPath, `${lines.join('\n')}\n`);
  console.log(`Wrote ${outPath} (${updated} updates)`);
}

main();
