-- Expand system exercise catalog — legs, glutes, unilateral, landmine-friendly, calisthenics.

insert into public.exercises (name, slug, category, equipment, muscle_groups, is_system, exercise_type, metadata) values
  ('Reverse Lunge', 'reverse-lunge', 'squat', 'bodyweight', array['quads', 'glutes'], true, 'strength',
    '{"requires":["bodyweight"],"movement_family":"lunge_pattern"}'::jsonb),
  ('Bulgarian Split Squat', 'bulgarian-split-squat', 'squat', 'dumbbell', array['quads', 'glutes'], true, 'strength',
    '{"requires":["dumbbells","bench"],"movement_family":"lunge_pattern"}'::jsonb),
  ('Step Up', 'step-up', 'squat', 'dumbbell', array['quads', 'glutes'], true, 'strength',
    '{"requires":["dumbbells","bench"],"movement_family":"lunge_pattern"}'::jsonb),
  ('Lateral Lunge', 'lateral-lunge', 'squat', 'bodyweight', array['quads', 'glutes'], true, 'strength',
    '{"requires":["bodyweight"],"movement_family":"lunge_pattern"}'::jsonb),
  ('Barbell Hip Thrust', 'hip-thrust', 'hinge', 'barbell', array['glutes', 'hamstrings'], true, 'strength',
    '{"requires":["barbell","bench"],"movement_family":"glute_pattern"}'::jsonb),
  ('Glute Bridge', 'glute-bridge', 'hinge', 'bodyweight', array['glutes', 'hamstrings'], true, 'strength',
    '{"requires":["bodyweight"],"movement_family":"glute_pattern"}'::jsonb),
  ('Single Leg RDL', 'single-leg-rdl', 'hinge', 'dumbbell', array['hamstrings', 'glutes'], true, 'strength',
    '{"requires":["dumbbells"],"movement_family":"hinge_pattern"}'::jsonb),
  ('Sumo Deadlift', 'sumo-deadlift', 'hinge', 'barbell', array['glutes', 'hamstrings', 'quads'], true, 'strength',
    '{"requires":["barbell","rack"],"movement_family":"hinge_pattern"}'::jsonb),
  ('Standing Calf Raise', 'standing-calf-raise', 'other', 'machine', array['calves'], true, 'strength',
    '{"requires":["machines"],"movement_family":"calves"}'::jsonb),
  ('Single Leg Calf Raise', 'single-leg-calf-raise', 'other', 'bodyweight', array['calves'], true, 'strength',
    '{"requires":["bodyweight"],"movement_family":"calves"}'::jsonb),
  ('Chin Up', 'chin-up', 'pull', 'bodyweight', array['back', 'biceps'], true, 'strength',
    '{"requires":["pull_up_bar"],"movement_family":"vertical_pull"}'::jsonb),
  ('Dip', 'dip', 'push', 'bodyweight', array['chest', 'triceps'], true, 'strength',
    '{"requires":["bodyweight"],"movement_family":"triceps"}'::jsonb),
  ('Hanging Leg Raise', 'hanging-leg-raise', 'core', 'bodyweight', array['core'], true, 'strength',
    '{"requires":["pull_up_bar"],"movement_family":"core_flexion"}'::jsonb),
  ('Landmine Squat', 'landmine-squat', 'squat', 'barbell', array['quads', 'glutes', 'core'], true, 'strength',
    '{"requires":["barbell","rack"],"movement_family":"squat_pattern"}'::jsonb),
  ('Landmine RDL', 'landmine-rdl', 'hinge', 'barbell', array['hamstrings', 'glutes'], true, 'strength',
    '{"requires":["barbell","rack"],"movement_family":"hinge_pattern"}'::jsonb),
  ('Pistol Squat', 'pistol-squat', 'squat', 'bodyweight', array['quads', 'glutes'], true, 'strength',
    '{"requires":["bodyweight"],"movement_family":"lunge_pattern"}'::jsonb),
  ('Face Pull', 'face-pull', 'pull', 'cable', array['shoulders', 'back'], true, 'strength',
    '{"requires":["machines"],"movement_family":"rear_delt"}'::jsonb),
  ('Hammer Curl', 'hammer-curl', 'pull', 'dumbbell', array['biceps'], true, 'strength',
    '{"requires":["dumbbells"],"movement_family":"biceps"}'::jsonb),
  ('Skull Crusher', 'skull-crusher', 'push', 'barbell', array['triceps'], true, 'strength',
    '{"requires":["barbell","bench"],"movement_family":"triceps"}'::jsonb),
  ('Incline Dumbbell Curl', 'incline-dumbbell-curl', 'pull', 'dumbbell', array['biceps'], true, 'strength',
    '{"requires":["dumbbells","bench"],"movement_family":"biceps"}'::jsonb)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  equipment = excluded.equipment,
  muscle_groups = excluded.muscle_groups,
  exercise_type = excluded.exercise_type,
  metadata = excluded.metadata;
