-- Remove duplicate system exercises that share the same display name.
-- Keeps 469 canonical exercises; removes 532 scaffold variant rows (107 duplicate name groups).
-- Generated by scripts/generate-dedupe-exercise-migration.mjs

create table if not exists public._migration_exercise_slug_remap (
  from_slug text primary key,
  to_slug text not null
);
truncate public._migration_exercise_slug_remap;

insert into public._migration_exercise_slug_remap (from_slug, to_slug) values
  ('45-degree-hyper-hm0668', '45-degree-hyper'),
  ('45-degree-hyper-hm0698', '45-degree-hyper'),
  ('45-degree-hyper-hm0728', '45-degree-hyper'),
  ('45-degree-hyper-hm0758', '45-degree-hyper'),
  ('45-degree-hyper-hm0788', '45-degree-hyper'),
  ('45-degree-hyper-hm0818', '45-degree-hyper'),
  ('anti-rotation-press-ch0886', 'anti-rotation-press'),
  ('anti-rotation-press-ch0916', 'anti-rotation-press'),
  ('anti-rotation-press-ch0946', 'anti-rotation-press'),
  ('anti-rotation-press-ch0976', 'anti-rotation-press'),
  ('archer-pull-up-ba0422', 'archer-pull-up'),
  ('back-extension-hm0248', 'back-extension'),
  ('back-extension-hm0278', 'back-extension'),
  ('back-extension-hm0308', 'back-extension'),
  ('back-extension-hm0338', 'back-extension'),
  ('back-extension-hm0368', 'back-extension'),
  ('back-extension-hm0398', 'back-extension'),
  ('band-pull-apart-sh0634', 'band-pull-apart'),
  ('band-pull-apart-sh0664', 'band-pull-apart'),
  ('band-pull-apart-sh0694', 'band-pull-apart'),
  ('band-pull-apart-sh0724', 'band-pull-apart'),
  ('band-pull-apart-sh0754', 'band-pull-apart'),
  ('band-pull-apart-sh0784', 'band-pull-apart'),
  ('band-pull-apart-sh0814', 'band-pull-apart'),
  ('bear-crawl-ca0464', 'bear-crawl'),
  ('bear-crawl-fu0225', 'bear-crawl'),
  ('bicycle-crunch-co0896', 'bicycle-crunch'),
  ('bicycle-crunch-co0926', 'bicycle-crunch'),
  ('bicycle-crunch-co0956', 'bicycle-crunch'),
  ('bicycle-crunch-co0986', 'bicycle-crunch'),
  ('box-squat-la0693', 'box-squat'),
  ('box-squat-la0723', 'box-squat'),
  ('box-squat-la0753', 'box-squat'),
  ('box-squat-la0783', 'box-squat'),
  ('box-squat-la0813', 'box-squat'),
  ('bulgarian-split-squat-qd0457', 'bulgarian-split-squat'),
  ('bulgarian-split-squat-qd0487', 'bulgarian-split-squat'),
  ('bulgarian-split-squat-qd0517', 'bulgarian-split-squat'),
  ('bulgarian-split-squat-qd0547', 'bulgarian-split-squat'),
  ('bulgarian-split-squat-qd0577', 'bulgarian-split-squat'),
  ('bulgarian-split-squat-qd0607', 'bulgarian-split-squat'),
  ('burpee-fu0030', 'burpee'),
  ('burpee-fu0060', 'burpee'),
  ('burpee-fu0090', 'burpee'),
  ('burpee-fu0120', 'burpee'),
  ('burpee-fu0150', 'burpee'),
  ('burpee-fu0180', 'burpee'),
  ('burpee-fu0210', 'burpee'),
  ('cable-fly-raise-sh0679', 'cable-fly-raise'),
  ('cable-fly-raise-sh0709', 'cable-fly-raise'),
  ('cable-fly-raise-sh0739', 'cable-fly-raise'),
  ('cable-fly-raise-sh0769', 'cable-fly-raise'),
  ('cable-fly-raise-sh0799', 'cable-fly-raise'),
  ('cable-fly-raise-sh0829', 'cable-fly-raise'),
  ('cable-kickback-gl0249', 'cable-kickback'),
  ('cable-kickback-gl0279', 'cable-kickback'),
  ('cable-kickback-gl0309', 'cable-kickback'),
  ('cable-kickback-gl0339', 'cable-kickback'),
  ('cable-kickback-gl0369', 'cable-kickback'),
  ('cable-kickback-gl0399', 'cable-kickback'),
  ('cable-pull-through-gl0684', 'cable-pull-through'),
  ('cable-pull-through-gl0714', 'cable-pull-through'),
  ('cable-pull-through-gl0744', 'cable-pull-through'),
  ('cable-pull-through-gl0774', 'cable-pull-through'),
  ('cable-pull-through-gl0804', 'cable-pull-through'),
  ('cable-pull-through-gl0834', 'cable-pull-through'),
  ('cable-wood-chop-ch0256', 'cable-wood-chop'),
  ('cable-wood-chop-ch0286', 'cable-wood-chop'),
  ('cable-wood-chop-ch0316', 'cable-wood-chop'),
  ('cable-wood-chop-ch0346', 'cable-wood-chop'),
  ('cable-wood-chop-ch0376', 'cable-wood-chop'),
  ('cable-wood-chop-ch0406', 'cable-wood-chop'),
  ('cable-wood-chop-co0446', 'cable-wood-chop'),
  ('cable-wood-chop-co0476', 'cable-wood-chop'),
  ('cable-wood-chop-co0506', 'cable-wood-chop'),
  ('cable-wood-chop-co0536', 'cable-wood-chop'),
  ('cable-wood-chop-co0566', 'cable-wood-chop'),
  ('cable-wood-chop-co0596', 'cable-wood-chop'),
  ('cable-wood-chop-co0626', 'cable-wood-chop'),
  ('calf-raise-walk-cv0895', 'calf-raise-walk');

insert into public._migration_exercise_slug_remap (from_slug, to_slug) values
  ('calf-raise-walk-cv0925', 'calf-raise-walk'),
  ('calf-raise-walk-cv0955', 'calf-raise-walk'),
  ('calf-raise-walk-cv0985', 'calf-raise-walk'),
  ('clean-and-press-fu0660', 'clean-and-press'),
  ('clean-and-press-fu0690', 'clean-and-press'),
  ('clean-and-press-fu0720', 'clean-and-press'),
  ('clean-and-press-fu0750', 'clean-and-press'),
  ('clean-and-press-fu0780', 'clean-and-press'),
  ('clean-and-press-fu0810', 'clean-and-press'),
  ('clean-and-press-fu0840', 'clean-and-press'),
  ('close-grip-bench-press-ch0691', 'close-grip-bench-press'),
  ('close-grip-pulldown-la0888', 'close-grip-pulldown'),
  ('commando-pull-up-la0408', 'commando-pull-up'),
  ('complex-circuit-fu0900', 'complex-circuit'),
  ('complex-circuit-fu0930', 'complex-circuit'),
  ('complex-circuit-fu0960', 'complex-circuit'),
  ('complex-circuit-fu0990', 'complex-circuit'),
  ('crab-walk-ca0674', 'crab-walk'),
  ('cross-body-extension-tr0666', 'cross-body-extension'),
  ('cross-body-extension-tr0696', 'cross-body-extension'),
  ('cross-body-extension-tr0726', 'cross-body-extension'),
  ('cross-body-extension-tr0756', 'cross-body-extension'),
  ('cross-body-extension-tr0786', 'cross-body-extension'),
  ('cross-body-extension-tr0816', 'cross-body-extension'),
  ('cycling-ca0554', 'cycling'),
  ('cycling-ca0584', 'cycling'),
  ('cycling-ca0614', 'cycling'),
  ('cycling-intervals-ca0599', 'cycling-intervals'),
  ('cycling-intervals-ca0629', 'cycling-intervals'),
  ('diamond-push-up-tr0561', 'diamond-push-up'),
  ('donkey-kick-gl0459', 'donkey-kick'),
  ('donkey-kick-gl0489', 'donkey-kick'),
  ('donkey-kick-gl0519', 'donkey-kick'),
  ('donkey-kick-gl0549', 'donkey-kick'),
  ('donkey-kick-gl0579', 'donkey-kick'),
  ('donkey-kick-gl0609', 'donkey-kick'),
  ('elliptical-ca0974', 'elliptical'),
  ('face-pull-ba0692', 'face-pull'),
  ('face-pull-sh0034', 'face-pull'),
  ('face-pull-sh0064', 'face-pull'),
  ('face-pull-sh0094', 'face-pull'),
  ('face-pull-sh0124', 'face-pull'),
  ('face-pull-sh0154', 'face-pull'),
  ('face-pull-sh0184', 'face-pull'),
  ('farmer-carry-bi0635', 'farmer-carry'),
  ('farmer-hold-walk-fa0267', 'farmer-hold-walk'),
  ('farmer-hold-walk-fa0297', 'farmer-hold-walk'),
  ('farmer-hold-walk-fa0327', 'farmer-hold-walk'),
  ('farmer-hold-walk-fa0357', 'farmer-hold-walk'),
  ('farmer-hold-walk-fa0387', 'farmer-hold-walk'),
  ('farmer-hold-walk-fa0417', 'farmer-hold-walk'),
  ('farmer-walk-on-toes-cv0055', 'farmer-walk-on-toes'),
  ('farmer-walk-on-toes-cv0085', 'farmer-walk-on-toes'),
  ('farmer-walk-on-toes-cv0115', 'farmer-walk-on-toes'),
  ('farmer-walk-on-toes-cv0145', 'farmer-walk-on-toes'),
  ('farmer-walk-on-toes-cv0175', 'farmer-walk-on-toes'),
  ('farmer-walk-on-toes-cv0205', 'farmer-walk-on-toes'),
  ('fire-hydrant-gl0669', 'fire-hydrant'),
  ('fire-hydrant-gl0699', 'fire-hydrant'),
  ('fire-hydrant-gl0729', 'fire-hydrant'),
  ('fire-hydrant-gl0759', 'fire-hydrant'),
  ('fire-hydrant-gl0789', 'fire-hydrant'),
  ('fire-hydrant-gl0819', 'fire-hydrant'),
  ('forearm-farmer-walk-fa0897', 'forearm-farmer-walk'),
  ('forearm-farmer-walk-fa0927', 'forearm-farmer-walk'),
  ('forearm-farmer-walk-fa0957', 'forearm-farmer-walk'),
  ('forearm-farmer-walk-fa0987', 'forearm-farmer-walk'),
  ('frog-pump-gl0894', 'frog-pump'),
  ('frog-pump-gl0924', 'frog-pump'),
  ('frog-pump-gl0954', 'frog-pump'),
  ('frog-pump-gl0984', 'frog-pump'),
  ('front-raise-sh0259', 'front-raise'),
  ('front-raise-sh0289', 'front-raise'),
  ('front-raise-sh0319', 'front-raise'),
  ('front-raise-sh0349', 'front-raise'),
  ('front-raise-sh0379', 'front-raise'),
  ('front-raise-sh0409', 'front-raise'),
  ('front-squat-la0273', 'front-squat'),
  ('front-squat-la0303', 'front-squat'),
  ('front-squat-la0333', 'front-squat');

insert into public._migration_exercise_slug_remap (from_slug, to_slug) values
  ('front-squat-la0363', 'front-squat'),
  ('front-squat-la0393', 'front-squat'),
  ('glute-bridge-gl0264', 'glute-bridge'),
  ('glute-bridge-gl0294', 'glute-bridge'),
  ('glute-bridge-gl0324', 'glute-bridge'),
  ('glute-bridge-gl0354', 'glute-bridge'),
  ('glute-bridge-gl0384', 'glute-bridge'),
  ('glute-bridge-gl0414', 'glute-bridge'),
  ('glute-kickback-gl0039', 'glute-kickback'),
  ('glute-kickback-gl0069', 'glute-kickback'),
  ('glute-kickback-gl0099', 'glute-kickback'),
  ('glute-kickback-gl0129', 'glute-kickback'),
  ('glute-kickback-gl0159', 'glute-kickback'),
  ('glute-kickback-gl0189', 'glute-kickback'),
  ('goblet-squat-la0063', 'goblet-squat'),
  ('goblet-squat-la0093', 'goblet-squat'),
  ('goblet-squat-la0123', 'goblet-squat'),
  ('goblet-squat-la0153', 'goblet-squat'),
  ('goblet-squat-la0183', 'goblet-squat'),
  ('good-morning-hm0038', 'good-morning'),
  ('good-morning-hm0068', 'good-morning'),
  ('good-morning-hm0098', 'good-morning'),
  ('good-morning-hm0128', 'good-morning'),
  ('good-morning-hm0158', 'good-morning'),
  ('good-morning-hm0188', 'good-morning'),
  ('grip-hold-march-fa0687', 'grip-hold-march'),
  ('grip-hold-march-fa0717', 'grip-hold-march'),
  ('grip-hold-march-fa0747', 'grip-hold-march'),
  ('grip-hold-march-fa0777', 'grip-hold-march'),
  ('grip-hold-march-fa0807', 'grip-hold-march'),
  ('grip-hold-march-fa0837', 'grip-hold-march'),
  ('hamstring-dominant-squat-hm0473', 'hamstring-dominant-squat'),
  ('hamstring-dominant-squat-hm0503', 'hamstring-dominant-squat'),
  ('hamstring-dominant-squat-hm0533', 'hamstring-dominant-squat'),
  ('hamstring-dominant-squat-hm0563', 'hamstring-dominant-squat'),
  ('hamstring-dominant-squat-hm0593', 'hamstring-dominant-squat'),
  ('hamstring-dominant-squat-hm0623', 'hamstring-dominant-squat'),
  ('heel-elevated-goblet-squat-la0483', 'heel-elevated-goblet-squat'),
  ('heel-elevated-goblet-squat-la0513', 'heel-elevated-goblet-squat'),
  ('heel-elevated-goblet-squat-la0543', 'heel-elevated-goblet-squat'),
  ('heel-elevated-goblet-squat-la0573', 'heel-elevated-goblet-squat'),
  ('heel-elevated-goblet-squat-la0603', 'heel-elevated-goblet-squat'),
  ('hip-abduction-gl0879', 'hip-abduction'),
  ('hip-abduction-gl0909', 'hip-abduction'),
  ('hip-abduction-gl0939', 'hip-abduction'),
  ('hip-abduction-gl0969', 'hip-abduction'),
  ('hip-abduction-gl0999', 'hip-abduction'),
  ('hip-thrust-gl0054', 'hip-thrust'),
  ('hip-thrust-gl0084', 'hip-thrust'),
  ('hip-thrust-gl0114', 'hip-thrust'),
  ('hip-thrust-gl0144', 'hip-thrust'),
  ('hip-thrust-gl0174', 'hip-thrust'),
  ('hip-thrust-gl0204', 'hip-thrust'),
  ('jefferson-curl-hm0683', 'jefferson-curl'),
  ('jefferson-curl-hm0713', 'jefferson-curl'),
  ('jefferson-curl-hm0743', 'jefferson-curl'),
  ('jefferson-curl-hm0773', 'jefferson-curl'),
  ('jefferson-curl-hm0803', 'jefferson-curl'),
  ('jefferson-curl-hm0833', 'jefferson-curl'),
  ('kneeling-overhead-extension-tr0876', 'kneeling-overhead-extension'),
  ('kneeling-overhead-extension-tr0906', 'kneeling-overhead-extension'),
  ('kneeling-overhead-extension-tr0936', 'kneeling-overhead-extension'),
  ('kneeling-overhead-extension-tr0966', 'kneeling-overhead-extension'),
  ('kneeling-overhead-extension-tr0996', 'kneeling-overhead-extension'),
  ('l-sit-pull-up-ba0632', 'l-sit-pull-up'),
  ('landmine-rotation-ch0436', 'landmine-rotation'),
  ('landmine-rotation-ch0466', 'landmine-rotation'),
  ('landmine-rotation-ch0496', 'landmine-rotation'),
  ('landmine-rotation-ch0526', 'landmine-rotation'),
  ('landmine-rotation-ch0556', 'landmine-rotation'),
  ('landmine-rotation-ch0586', 'landmine-rotation'),
  ('landmine-rotation-ch0616', 'landmine-rotation'),
  ('landmine-rotation-co0656', 'landmine-rotation'),
  ('landmine-rotation-co0686', 'landmine-rotation'),
  ('landmine-rotation-co0716', 'landmine-rotation'),
  ('landmine-rotation-co0746', 'landmine-rotation'),
  ('landmine-rotation-co0776', 'landmine-rotation'),
  ('landmine-rotation-co0806', 'landmine-rotation'),
  ('landmine-rotation-co0836', 'landmine-rotation'),
  ('lat-pulldown-ba0272', 'lat-pulldown');

insert into public._migration_exercise_slug_remap (from_slug, to_slug) values
  ('lat-pulldown-la0048', 'lat-pulldown'),
  ('lateral-lunge-qd0667', 'lateral-lunge'),
  ('lateral-lunge-qd0697', 'lateral-lunge'),
  ('lateral-lunge-qd0727', 'lateral-lunge'),
  ('lateral-lunge-qd0757', 'lateral-lunge'),
  ('lateral-lunge-qd0787', 'lateral-lunge'),
  ('lateral-lunge-qd0817', 'lateral-lunge'),
  ('lateral-raise-sh0049', 'lateral-raise'),
  ('lateral-raise-sh0079', 'lateral-raise'),
  ('lateral-raise-sh0109', 'lateral-raise'),
  ('lateral-raise-sh0139', 'lateral-raise'),
  ('lateral-raise-sh0169', 'lateral-raise'),
  ('lateral-raise-sh0199', 'lateral-raise'),
  ('leg-extension-qd0052', 'leg-extension'),
  ('leg-extension-qd0082', 'leg-extension'),
  ('leg-extension-qd0112', 'leg-extension'),
  ('leg-extension-qd0142', 'leg-extension'),
  ('leg-extension-qd0172', 'leg-extension'),
  ('leg-extension-qd0202', 'leg-extension'),
  ('man-maker-fu0480', 'man-maker'),
  ('man-maker-fu0510', 'man-maker'),
  ('man-maker-fu0540', 'man-maker'),
  ('man-maker-fu0570', 'man-maker'),
  ('man-maker-fu0600', 'man-maker'),
  ('man-maker-fu0630', 'man-maker'),
  ('medicine-ball-twist-ch0676', 'medicine-ball-twist'),
  ('medicine-ball-twist-ch0706', 'medicine-ball-twist'),
  ('medicine-ball-twist-ch0736', 'medicine-ball-twist'),
  ('medicine-ball-twist-ch0766', 'medicine-ball-twist'),
  ('medicine-ball-twist-ch0796', 'medicine-ball-twist'),
  ('medicine-ball-twist-ch0826', 'medicine-ball-twist'),
  ('neck-extension-nc0463', 'neck-extension'),
  ('neck-extension-nc0493', 'neck-extension'),
  ('neck-extension-nc0523', 'neck-extension'),
  ('neck-extension-nc0553', 'neck-extension'),
  ('neck-extension-nc0583', 'neck-extension'),
  ('neck-extension-nc0613', 'neck-extension'),
  ('neck-extension-press-nc0478', 'neck-extension-press'),
  ('neck-extension-press-nc0508', 'neck-extension-press'),
  ('neck-extension-press-nc0538', 'neck-extension-press'),
  ('neck-extension-press-nc0568', 'neck-extension-press'),
  ('neck-extension-press-nc0598', 'neck-extension-press'),
  ('neck-extension-press-nc0628', 'neck-extension-press'),
  ('neck-flexion-nc0253', 'neck-flexion'),
  ('neck-flexion-nc0283', 'neck-flexion'),
  ('neck-flexion-nc0313', 'neck-flexion'),
  ('neck-flexion-nc0343', 'neck-flexion'),
  ('neck-flexion-nc0373', 'neck-flexion'),
  ('neck-flexion-nc0403', 'neck-flexion'),
  ('neck-flexion-press-nc0268', 'neck-flexion-press'),
  ('neck-flexion-press-nc0298', 'neck-flexion-press'),
  ('neck-flexion-press-nc0328', 'neck-flexion-press'),
  ('neck-flexion-press-nc0358', 'neck-flexion-press'),
  ('neck-flexion-press-nc0388', 'neck-flexion-press'),
  ('neck-flexion-press-nc0418', 'neck-flexion-press'),
  ('neck-isometric-hold-nc0043', 'neck-isometric-hold'),
  ('neck-isometric-hold-nc0073', 'neck-isometric-hold'),
  ('neck-isometric-hold-nc0103', 'neck-isometric-hold'),
  ('neck-isometric-hold-nc0133', 'neck-isometric-hold'),
  ('neck-isometric-hold-nc0163', 'neck-isometric-hold'),
  ('neck-isometric-hold-nc0193', 'neck-isometric-hold'),
  ('neck-isometric-hold-press-nc0058', 'neck-isometric-hold-press'),
  ('neck-isometric-hold-press-nc0088', 'neck-isometric-hold-press'),
  ('neck-isometric-hold-press-nc0118', 'neck-isometric-hold-press'),
  ('neck-isometric-hold-press-nc0148', 'neck-isometric-hold-press'),
  ('neck-isometric-hold-press-nc0178', 'neck-isometric-hold-press'),
  ('neck-isometric-hold-press-nc0208', 'neck-isometric-hold-press'),
  ('neck-lateral-flexion-nc0673', 'neck-lateral-flexion'),
  ('neck-lateral-flexion-nc0703', 'neck-lateral-flexion'),
  ('neck-lateral-flexion-nc0733', 'neck-lateral-flexion'),
  ('neck-lateral-flexion-nc0763', 'neck-lateral-flexion'),
  ('neck-lateral-flexion-nc0793', 'neck-lateral-flexion'),
  ('neck-lateral-flexion-nc0823', 'neck-lateral-flexion'),
  ('neck-lateral-flexion-press-nc0688', 'neck-lateral-flexion-press'),
  ('neck-lateral-flexion-press-nc0718', 'neck-lateral-flexion-press'),
  ('neck-lateral-flexion-press-nc0748', 'neck-lateral-flexion-press'),
  ('neck-lateral-flexion-press-nc0778', 'neck-lateral-flexion-press'),
  ('neck-lateral-flexion-press-nc0808', 'neck-lateral-flexion-press'),
  ('neck-lateral-flexion-press-nc0838', 'neck-lateral-flexion-press'),
  ('neck-rotation-nc0883', 'neck-rotation');

insert into public._migration_exercise_slug_remap (from_slug, to_slug) values
  ('neck-rotation-nc0913', 'neck-rotation'),
  ('neck-rotation-nc0943', 'neck-rotation'),
  ('neck-rotation-nc0973', 'neck-rotation'),
  ('neck-rotation-press-nc0898', 'neck-rotation-press'),
  ('neck-rotation-press-nc0928', 'neck-rotation-press'),
  ('neck-rotation-press-nc0958', 'neck-rotation-press'),
  ('neck-rotation-press-nc0988', 'neck-rotation-press'),
  ('nordic-curl-hm0053', 'nordic-curl'),
  ('nordic-curl-hm0083', 'nordic-curl'),
  ('nordic-curl-hm0113', 'nordic-curl'),
  ('nordic-curl-hm0143', 'nordic-curl'),
  ('nordic-curl-hm0173', 'nordic-curl'),
  ('nordic-curl-hm0203', 'nordic-curl'),
  ('overhead-carry-bi0845', 'overhead-carry'),
  ('overhead-tricep-extension-tr0036', 'overhead-tricep-extension'),
  ('overhead-tricep-extension-tr0066', 'overhead-tricep-extension'),
  ('overhead-tricep-extension-tr0096', 'overhead-tricep-extension'),
  ('overhead-tricep-extension-tr0126', 'overhead-tricep-extension'),
  ('overhead-tricep-extension-tr0156', 'overhead-tricep-extension'),
  ('overhead-tricep-extension-tr0186', 'overhead-tricep-extension'),
  ('overhead-tricep-extension-tr0831', 'overhead-tricep-extension'),
  ('pallof-press-ch0046', 'pallof-press'),
  ('pallof-press-ch0076', 'pallof-press'),
  ('pallof-press-ch0106', 'pallof-press'),
  ('pallof-press-ch0136', 'pallof-press'),
  ('pallof-press-ch0166', 'pallof-press'),
  ('pallof-press-ch0196', 'pallof-press'),
  ('pallof-press-co0236', 'pallof-press'),
  ('pallof-press-co0266', 'pallof-press'),
  ('pallof-press-co0296', 'pallof-press'),
  ('pallof-press-co0326', 'pallof-press'),
  ('pallof-press-co0356', 'pallof-press'),
  ('pallof-press-co0386', 'pallof-press'),
  ('pallof-press-co0416', 'pallof-press'),
  ('pause-squat-la0903', 'pause-squat'),
  ('pause-squat-la0933', 'pause-squat'),
  ('pause-squat-la0963', 'pause-squat'),
  ('pause-squat-la0993', 'pause-squat'),
  ('plate-pinch-walk-fa0477', 'plate-pinch-walk'),
  ('plate-pinch-walk-fa0507', 'plate-pinch-walk'),
  ('plate-pinch-walk-fa0537', 'plate-pinch-walk'),
  ('plate-pinch-walk-fa0567', 'plate-pinch-walk'),
  ('plate-pinch-walk-fa0597', 'plate-pinch-walk'),
  ('plate-pinch-walk-fa0627', 'plate-pinch-walk'),
  ('poliquin-step-up-qd0892', 'poliquin-step-up'),
  ('poliquin-step-up-qd0922', 'poliquin-step-up'),
  ('poliquin-step-up-qd0952', 'poliquin-step-up'),
  ('poliquin-step-up-qd0982', 'poliquin-step-up'),
  ('rear-delt-fly-sh0439', 'rear-delt-fly'),
  ('rear-delt-fly-sh0454', 'rear-delt-fly'),
  ('rear-delt-fly-sh0469', 'rear-delt-fly'),
  ('rear-delt-fly-sh0484', 'rear-delt-fly'),
  ('rear-delt-fly-sh0499', 'rear-delt-fly'),
  ('rear-delt-fly-sh0514', 'rear-delt-fly'),
  ('rear-delt-fly-sh0529', 'rear-delt-fly'),
  ('rear-delt-fly-sh0544', 'rear-delt-fly'),
  ('rear-delt-fly-sh0559', 'rear-delt-fly'),
  ('rear-delt-fly-sh0574', 'rear-delt-fly'),
  ('rear-delt-fly-sh0589', 'rear-delt-fly'),
  ('rear-delt-fly-sh0604', 'rear-delt-fly'),
  ('rear-delt-fly-sh0619', 'rear-delt-fly'),
  ('reverse-fly-sh0244', 'reverse-fly'),
  ('reverse-fly-sh0274', 'reverse-fly'),
  ('reverse-fly-sh0304', 'reverse-fly'),
  ('reverse-fly-sh0334', 'reverse-fly'),
  ('reverse-fly-sh0364', 'reverse-fly'),
  ('reverse-fly-sh0394', 'reverse-fly'),
  ('reverse-hyper-hm0458', 'reverse-hyper'),
  ('reverse-hyper-hm0488', 'reverse-hyper'),
  ('reverse-hyper-hm0518', 'reverse-hyper'),
  ('reverse-hyper-hm0548', 'reverse-hyper'),
  ('reverse-hyper-hm0578', 'reverse-hyper'),
  ('reverse-hyper-hm0608', 'reverse-hyper'),
  ('reverse-lunge-qd0247', 'reverse-lunge'),
  ('reverse-lunge-qd0277', 'reverse-lunge'),
  ('reverse-lunge-qd0307', 'reverse-lunge'),
  ('reverse-lunge-qd0337', 'reverse-lunge'),
  ('reverse-lunge-qd0367', 'reverse-lunge'),
  ('reverse-lunge-qd0397', 'reverse-lunge'),
  ('rope-overhead-extension-tr0456', 'rope-overhead-extension');

insert into public._migration_exercise_slug_remap (from_slug, to_slug) values
  ('rope-overhead-extension-tr0486', 'rope-overhead-extension'),
  ('rope-overhead-extension-tr0516', 'rope-overhead-extension'),
  ('rope-overhead-extension-tr0546', 'rope-overhead-extension'),
  ('rope-overhead-extension-tr0576', 'rope-overhead-extension'),
  ('rope-overhead-extension-tr0606', 'rope-overhead-extension'),
  ('rowing-ca0344', 'rowing'),
  ('rowing-ca0374', 'rowing'),
  ('rowing-ca0404', 'rowing'),
  ('rowing-intervals-ca0389', 'rowing-intervals'),
  ('rowing-intervals-ca0419', 'rowing-intervals'),
  ('running-ca0134', 'running'),
  ('running-ca0164', 'running'),
  ('running-ca0194', 'running'),
  ('running-intervals-ca0179', 'running-intervals'),
  ('running-intervals-ca0209', 'running-intervals'),
  ('russian-twist-co0056', 'russian-twist'),
  ('russian-twist-co0086', 'russian-twist'),
  ('russian-twist-co0116', 'russian-twist'),
  ('russian-twist-co0146', 'russian-twist'),
  ('russian-twist-co0176', 'russian-twist'),
  ('russian-twist-co0206', 'russian-twist'),
  ('scapular-wall-slide-sh0874', 'scapular-wall-slide'),
  ('scapular-wall-slide-sh0904', 'scapular-wall-slide'),
  ('scapular-wall-slide-sh0934', 'scapular-wall-slide'),
  ('scapular-wall-slide-sh0964', 'scapular-wall-slide'),
  ('scapular-wall-slide-sh0994', 'scapular-wall-slide'),
  ('seated-calf-hold-walk-cv0475', 'seated-calf-hold-walk'),
  ('seated-calf-hold-walk-cv0505', 'seated-calf-hold-walk'),
  ('seated-calf-hold-walk-cv0535', 'seated-calf-hold-walk'),
  ('seated-calf-hold-walk-cv0565', 'seated-calf-hold-walk'),
  ('seated-calf-hold-walk-cv0595', 'seated-calf-hold-walk'),
  ('seated-calf-hold-walk-cv0625', 'seated-calf-hold-walk'),
  ('seated-good-morning-hm0878', 'seated-good-morning'),
  ('seated-good-morning-hm0908', 'seated-good-morning'),
  ('seated-good-morning-hm0938', 'seated-good-morning'),
  ('seated-good-morning-hm0968', 'seated-good-morning'),
  ('seated-good-morning-hm0998', 'seated-good-morning'),
  ('single-arm-tricep-extension-tr0246', 'single-arm-tricep-extension'),
  ('single-arm-tricep-extension-tr0276', 'single-arm-tricep-extension'),
  ('single-arm-tricep-extension-tr0306', 'single-arm-tricep-extension'),
  ('single-arm-tricep-extension-tr0336', 'single-arm-tricep-extension'),
  ('single-arm-tricep-extension-tr0366', 'single-arm-tricep-extension'),
  ('single-arm-tricep-extension-tr0396', 'single-arm-tricep-extension'),
  ('single-leg-calf-walk-cv0265', 'single-leg-calf-walk'),
  ('single-leg-calf-walk-cv0295', 'single-leg-calf-walk'),
  ('single-leg-calf-walk-cv0325', 'single-leg-calf-walk'),
  ('single-leg-calf-walk-cv0355', 'single-leg-calf-walk'),
  ('single-leg-calf-walk-cv0385', 'single-leg-calf-walk'),
  ('single-leg-calf-walk-cv0415', 'single-leg-calf-walk'),
  ('single-leg-hip-thrust-gl0474', 'single-leg-hip-thrust'),
  ('single-leg-hip-thrust-gl0504', 'single-leg-hip-thrust'),
  ('single-leg-hip-thrust-gl0534', 'single-leg-hip-thrust'),
  ('single-leg-hip-thrust-gl0564', 'single-leg-hip-thrust'),
  ('single-leg-hip-thrust-gl0594', 'single-leg-hip-thrust'),
  ('single-leg-hip-thrust-gl0624', 'single-leg-hip-thrust'),
  ('sissy-squat-hm0863', 'sissy-squat'),
  ('sissy-squat-hm0893', 'sissy-squat'),
  ('sissy-squat-hm0923', 'sissy-squat'),
  ('sissy-squat-hm0953', 'sissy-squat'),
  ('sissy-squat-hm0983', 'sissy-squat'),
  ('sissy-squat-qd0262', 'sissy-squat'),
  ('sissy-squat-qd0292', 'sissy-squat'),
  ('sissy-squat-qd0322', 'sissy-squat'),
  ('sissy-squat-qd0352', 'sissy-squat'),
  ('sissy-squat-qd0382', 'sissy-squat'),
  ('sissy-squat-qd0412', 'sissy-squat'),
  ('slider-hamstring-curl-hm0263', 'slider-hamstring-curl'),
  ('slider-hamstring-curl-hm0293', 'slider-hamstring-curl'),
  ('slider-hamstring-curl-hm0323', 'slider-hamstring-curl'),
  ('slider-hamstring-curl-hm0353', 'slider-hamstring-curl'),
  ('slider-hamstring-curl-hm0383', 'slider-hamstring-curl'),
  ('slider-hamstring-curl-hm0413', 'slider-hamstring-curl'),
  ('smith-close-grip-press-ch0781', 'smith-close-grip-press'),
  ('smith-floor-press-ch0991', 'smith-floor-press'),
  ('spanish-squat-qd0682', 'spanish-squat'),
  ('spanish-squat-qd0712', 'spanish-squat'),
  ('spanish-squat-qd0742', 'spanish-squat'),
  ('spanish-squat-qd0772', 'spanish-squat'),
  ('spanish-squat-qd0802', 'spanish-squat'),
  ('spanish-squat-qd0832', 'spanish-squat');

insert into public._migration_exercise_slug_remap (from_slug, to_slug) values
  ('step-up-qd0877', 'step-up'),
  ('step-up-qd0907', 'step-up'),
  ('step-up-qd0937', 'step-up'),
  ('step-up-qd0967', 'step-up'),
  ('step-up-qd0997', 'step-up'),
  ('straight-arm-pulldown-ba0482', 'straight-arm-pulldown'),
  ('straight-arm-pulldown-la0438', 'straight-arm-pulldown'),
  ('swimming-ca0764', 'swimming'),
  ('swimming-ca0794', 'swimming'),
  ('swimming-ca0824', 'swimming'),
  ('swimming-intervals-ca0809', 'swimming-intervals'),
  ('swimming-intervals-ca0839', 'swimming-intervals'),
  ('terminal-knee-extension-qd0472', 'terminal-knee-extension'),
  ('terminal-knee-extension-qd0502', 'terminal-knee-extension'),
  ('terminal-knee-extension-qd0532', 'terminal-knee-extension'),
  ('terminal-knee-extension-qd0562', 'terminal-knee-extension'),
  ('terminal-knee-extension-qd0592', 'terminal-knee-extension'),
  ('terminal-knee-extension-qd0622', 'terminal-knee-extension'),
  ('thruster-fu0270', 'thruster'),
  ('thruster-fu0300', 'thruster'),
  ('thruster-fu0330', 'thruster'),
  ('thruster-fu0360', 'thruster'),
  ('thruster-fu0390', 'thruster'),
  ('thruster-fu0420', 'thruster'),
  ('thruster-fu0915', 'thruster'),
  ('trap-bar-close-grip-press-ch0541', 'trap-bar-close-grip-press'),
  ('trap-bar-floor-press-tr0891', 'trap-bar-floor-press'),
  ('typewriter-pull-up-ba0842', 'typewriter-pull-up'),
  ('walking-lunge-ba0407', 'walking-lunge'),
  ('walking-lunge-qd0037', 'walking-lunge'),
  ('walking-lunge-qd0067', 'walking-lunge'),
  ('walking-lunge-qd0097', 'walking-lunge'),
  ('walking-lunge-qd0127', 'walking-lunge'),
  ('walking-lunge-qd0157', 'walking-lunge'),
  ('walking-lunge-qd0187', 'walking-lunge'),
  ('weighted-calf-march-cv0685', 'weighted-calf-march'),
  ('weighted-calf-march-cv0715', 'weighted-calf-march'),
  ('weighted-calf-march-cv0745', 'weighted-calf-march'),
  ('weighted-calf-march-cv0775', 'weighted-calf-march'),
  ('weighted-calf-march-cv0805', 'weighted-calf-march'),
  ('weighted-calf-march-cv0835', 'weighted-calf-march'),
  ('wide-lat-pulldown-la0678', 'wide-lat-pulldown'),
  ('wrist-roller-walk-fa0057', 'wrist-roller-walk'),
  ('wrist-roller-walk-fa0087', 'wrist-roller-walk'),
  ('wrist-roller-walk-fa0117', 'wrist-roller-walk'),
  ('wrist-roller-walk-fa0147', 'wrist-roller-walk'),
  ('wrist-roller-walk-fa0177', 'wrist-roller-walk'),
  ('wrist-roller-walk-fa0207', 'wrist-roller-walk'),
  ('y-raise-sh0889', 'y-raise'),
  ('y-raise-sh0919', 'y-raise'),
  ('y-raise-sh0949', 'y-raise'),
  ('y-raise-sh0979', 'y-raise');

-- Drop custom-exercise rows that would violate unique(user_id, exercise_id) after remap.
delete from public.user_custom_exercises uce
using public.exercises dup
join public._migration_exercise_slug_remap m on m.from_slug = dup.slug
join public.exercises canon on canon.slug = m.to_slug
where uce.exercise_id = dup.id
  and exists (
    select 1
    from public.user_custom_exercises existing
    where existing.user_id = uce.user_id
      and existing.exercise_id = canon.id
  );

update public.workout_exercises we
set exercise_id = canon.id
from public.exercises dup
join public._migration_exercise_slug_remap m on m.from_slug = dup.slug
join public.exercises canon on canon.slug = m.to_slug
where we.exercise_id = dup.id;

update public.user_custom_exercises uce
set exercise_id = canon.id
from public.exercises dup
join public._migration_exercise_slug_remap m on m.from_slug = dup.slug
join public.exercises canon on canon.slug = m.to_slug
where uce.exercise_id = dup.id;

update public.performance_trends pt
set exercise_id = canon.id
from public.exercises dup
join public._migration_exercise_slug_remap m on m.from_slug = dup.slug
join public.exercises canon on canon.slug = m.to_slug
where pt.exercise_id = dup.id;

update public.exercise_recognition_events ere
set suggested_exercise_id = canon.id
from public.exercises dup
join public._migration_exercise_slug_remap m on m.from_slug = dup.slug
join public.exercises canon on canon.slug = m.to_slug
where ere.suggested_exercise_id = dup.id;

delete from public.exercises
where is_system = true
  and slug in ('45-degree-hyper-hm0668', '45-degree-hyper-hm0698', '45-degree-hyper-hm0728', '45-degree-hyper-hm0758', '45-degree-hyper-hm0788', '45-degree-hyper-hm0818', 'anti-rotation-press-ch0886', 'anti-rotation-press-ch0916', 'anti-rotation-press-ch0946', 'anti-rotation-press-ch0976', 'archer-pull-up-ba0422', 'back-extension-hm0248', 'back-extension-hm0278', 'back-extension-hm0308', 'back-extension-hm0338', 'back-extension-hm0368', 'back-extension-hm0398', 'band-pull-apart-sh0634', 'band-pull-apart-sh0664', 'band-pull-apart-sh0694', 'band-pull-apart-sh0724', 'band-pull-apart-sh0754', 'band-pull-apart-sh0784', 'band-pull-apart-sh0814', 'bear-crawl-ca0464', 'bear-crawl-fu0225', 'bicycle-crunch-co0896', 'bicycle-crunch-co0926', 'bicycle-crunch-co0956', 'bicycle-crunch-co0986', 'box-squat-la0693', 'box-squat-la0723', 'box-squat-la0753', 'box-squat-la0783', 'box-squat-la0813', 'bulgarian-split-squat-qd0457', 'bulgarian-split-squat-qd0487', 'bulgarian-split-squat-qd0517', 'bulgarian-split-squat-qd0547', 'bulgarian-split-squat-qd0577');

delete from public.exercises
where is_system = true
  and slug in ('bulgarian-split-squat-qd0607', 'burpee-fu0030', 'burpee-fu0060', 'burpee-fu0090', 'burpee-fu0120', 'burpee-fu0150', 'burpee-fu0180', 'burpee-fu0210', 'cable-fly-raise-sh0679', 'cable-fly-raise-sh0709', 'cable-fly-raise-sh0739', 'cable-fly-raise-sh0769', 'cable-fly-raise-sh0799', 'cable-fly-raise-sh0829', 'cable-kickback-gl0249', 'cable-kickback-gl0279', 'cable-kickback-gl0309', 'cable-kickback-gl0339', 'cable-kickback-gl0369', 'cable-kickback-gl0399', 'cable-pull-through-gl0684', 'cable-pull-through-gl0714', 'cable-pull-through-gl0744', 'cable-pull-through-gl0774', 'cable-pull-through-gl0804', 'cable-pull-through-gl0834', 'cable-wood-chop-ch0256', 'cable-wood-chop-ch0286', 'cable-wood-chop-ch0316', 'cable-wood-chop-ch0346', 'cable-wood-chop-ch0376', 'cable-wood-chop-ch0406', 'cable-wood-chop-co0446', 'cable-wood-chop-co0476', 'cable-wood-chop-co0506', 'cable-wood-chop-co0536', 'cable-wood-chop-co0566', 'cable-wood-chop-co0596', 'cable-wood-chop-co0626', 'calf-raise-walk-cv0895');

delete from public.exercises
where is_system = true
  and slug in ('calf-raise-walk-cv0925', 'calf-raise-walk-cv0955', 'calf-raise-walk-cv0985', 'clean-and-press-fu0660', 'clean-and-press-fu0690', 'clean-and-press-fu0720', 'clean-and-press-fu0750', 'clean-and-press-fu0780', 'clean-and-press-fu0810', 'clean-and-press-fu0840', 'close-grip-bench-press-ch0691', 'close-grip-pulldown-la0888', 'commando-pull-up-la0408', 'complex-circuit-fu0900', 'complex-circuit-fu0930', 'complex-circuit-fu0960', 'complex-circuit-fu0990', 'crab-walk-ca0674', 'cross-body-extension-tr0666', 'cross-body-extension-tr0696', 'cross-body-extension-tr0726', 'cross-body-extension-tr0756', 'cross-body-extension-tr0786', 'cross-body-extension-tr0816', 'cycling-ca0554', 'cycling-ca0584', 'cycling-ca0614', 'cycling-intervals-ca0599', 'cycling-intervals-ca0629', 'diamond-push-up-tr0561', 'donkey-kick-gl0459', 'donkey-kick-gl0489', 'donkey-kick-gl0519', 'donkey-kick-gl0549', 'donkey-kick-gl0579', 'donkey-kick-gl0609', 'elliptical-ca0974', 'face-pull-ba0692', 'face-pull-sh0034', 'face-pull-sh0064');

delete from public.exercises
where is_system = true
  and slug in ('face-pull-sh0094', 'face-pull-sh0124', 'face-pull-sh0154', 'face-pull-sh0184', 'farmer-carry-bi0635', 'farmer-hold-walk-fa0267', 'farmer-hold-walk-fa0297', 'farmer-hold-walk-fa0327', 'farmer-hold-walk-fa0357', 'farmer-hold-walk-fa0387', 'farmer-hold-walk-fa0417', 'farmer-walk-on-toes-cv0055', 'farmer-walk-on-toes-cv0085', 'farmer-walk-on-toes-cv0115', 'farmer-walk-on-toes-cv0145', 'farmer-walk-on-toes-cv0175', 'farmer-walk-on-toes-cv0205', 'fire-hydrant-gl0669', 'fire-hydrant-gl0699', 'fire-hydrant-gl0729', 'fire-hydrant-gl0759', 'fire-hydrant-gl0789', 'fire-hydrant-gl0819', 'forearm-farmer-walk-fa0897', 'forearm-farmer-walk-fa0927', 'forearm-farmer-walk-fa0957', 'forearm-farmer-walk-fa0987', 'frog-pump-gl0894', 'frog-pump-gl0924', 'frog-pump-gl0954', 'frog-pump-gl0984', 'front-raise-sh0259', 'front-raise-sh0289', 'front-raise-sh0319', 'front-raise-sh0349', 'front-raise-sh0379', 'front-raise-sh0409', 'front-squat-la0273', 'front-squat-la0303', 'front-squat-la0333');

delete from public.exercises
where is_system = true
  and slug in ('front-squat-la0363', 'front-squat-la0393', 'glute-bridge-gl0264', 'glute-bridge-gl0294', 'glute-bridge-gl0324', 'glute-bridge-gl0354', 'glute-bridge-gl0384', 'glute-bridge-gl0414', 'glute-kickback-gl0039', 'glute-kickback-gl0069', 'glute-kickback-gl0099', 'glute-kickback-gl0129', 'glute-kickback-gl0159', 'glute-kickback-gl0189', 'goblet-squat-la0063', 'goblet-squat-la0093', 'goblet-squat-la0123', 'goblet-squat-la0153', 'goblet-squat-la0183', 'good-morning-hm0038', 'good-morning-hm0068', 'good-morning-hm0098', 'good-morning-hm0128', 'good-morning-hm0158', 'good-morning-hm0188', 'grip-hold-march-fa0687', 'grip-hold-march-fa0717', 'grip-hold-march-fa0747', 'grip-hold-march-fa0777', 'grip-hold-march-fa0807', 'grip-hold-march-fa0837', 'hamstring-dominant-squat-hm0473', 'hamstring-dominant-squat-hm0503', 'hamstring-dominant-squat-hm0533', 'hamstring-dominant-squat-hm0563', 'hamstring-dominant-squat-hm0593', 'hamstring-dominant-squat-hm0623', 'heel-elevated-goblet-squat-la0483', 'heel-elevated-goblet-squat-la0513', 'heel-elevated-goblet-squat-la0543');

delete from public.exercises
where is_system = true
  and slug in ('heel-elevated-goblet-squat-la0573', 'heel-elevated-goblet-squat-la0603', 'hip-abduction-gl0879', 'hip-abduction-gl0909', 'hip-abduction-gl0939', 'hip-abduction-gl0969', 'hip-abduction-gl0999', 'hip-thrust-gl0054', 'hip-thrust-gl0084', 'hip-thrust-gl0114', 'hip-thrust-gl0144', 'hip-thrust-gl0174', 'hip-thrust-gl0204', 'jefferson-curl-hm0683', 'jefferson-curl-hm0713', 'jefferson-curl-hm0743', 'jefferson-curl-hm0773', 'jefferson-curl-hm0803', 'jefferson-curl-hm0833', 'kneeling-overhead-extension-tr0876', 'kneeling-overhead-extension-tr0906', 'kneeling-overhead-extension-tr0936', 'kneeling-overhead-extension-tr0966', 'kneeling-overhead-extension-tr0996', 'l-sit-pull-up-ba0632', 'landmine-rotation-ch0436', 'landmine-rotation-ch0466', 'landmine-rotation-ch0496', 'landmine-rotation-ch0526', 'landmine-rotation-ch0556', 'landmine-rotation-ch0586', 'landmine-rotation-ch0616', 'landmine-rotation-co0656', 'landmine-rotation-co0686', 'landmine-rotation-co0716', 'landmine-rotation-co0746', 'landmine-rotation-co0776', 'landmine-rotation-co0806', 'landmine-rotation-co0836', 'lat-pulldown-ba0272');

delete from public.exercises
where is_system = true
  and slug in ('lat-pulldown-la0048', 'lateral-lunge-qd0667', 'lateral-lunge-qd0697', 'lateral-lunge-qd0727', 'lateral-lunge-qd0757', 'lateral-lunge-qd0787', 'lateral-lunge-qd0817', 'lateral-raise-sh0049', 'lateral-raise-sh0079', 'lateral-raise-sh0109', 'lateral-raise-sh0139', 'lateral-raise-sh0169', 'lateral-raise-sh0199', 'leg-extension-qd0052', 'leg-extension-qd0082', 'leg-extension-qd0112', 'leg-extension-qd0142', 'leg-extension-qd0172', 'leg-extension-qd0202', 'man-maker-fu0480', 'man-maker-fu0510', 'man-maker-fu0540', 'man-maker-fu0570', 'man-maker-fu0600', 'man-maker-fu0630', 'medicine-ball-twist-ch0676', 'medicine-ball-twist-ch0706', 'medicine-ball-twist-ch0736', 'medicine-ball-twist-ch0766', 'medicine-ball-twist-ch0796', 'medicine-ball-twist-ch0826', 'neck-extension-nc0463', 'neck-extension-nc0493', 'neck-extension-nc0523', 'neck-extension-nc0553', 'neck-extension-nc0583', 'neck-extension-nc0613', 'neck-extension-press-nc0478', 'neck-extension-press-nc0508', 'neck-extension-press-nc0538');

delete from public.exercises
where is_system = true
  and slug in ('neck-extension-press-nc0568', 'neck-extension-press-nc0598', 'neck-extension-press-nc0628', 'neck-flexion-nc0253', 'neck-flexion-nc0283', 'neck-flexion-nc0313', 'neck-flexion-nc0343', 'neck-flexion-nc0373', 'neck-flexion-nc0403', 'neck-flexion-press-nc0268', 'neck-flexion-press-nc0298', 'neck-flexion-press-nc0328', 'neck-flexion-press-nc0358', 'neck-flexion-press-nc0388', 'neck-flexion-press-nc0418', 'neck-isometric-hold-nc0043', 'neck-isometric-hold-nc0073', 'neck-isometric-hold-nc0103', 'neck-isometric-hold-nc0133', 'neck-isometric-hold-nc0163', 'neck-isometric-hold-nc0193', 'neck-isometric-hold-press-nc0058', 'neck-isometric-hold-press-nc0088', 'neck-isometric-hold-press-nc0118', 'neck-isometric-hold-press-nc0148', 'neck-isometric-hold-press-nc0178', 'neck-isometric-hold-press-nc0208', 'neck-lateral-flexion-nc0673', 'neck-lateral-flexion-nc0703', 'neck-lateral-flexion-nc0733', 'neck-lateral-flexion-nc0763', 'neck-lateral-flexion-nc0793', 'neck-lateral-flexion-nc0823', 'neck-lateral-flexion-press-nc0688', 'neck-lateral-flexion-press-nc0718', 'neck-lateral-flexion-press-nc0748', 'neck-lateral-flexion-press-nc0778', 'neck-lateral-flexion-press-nc0808', 'neck-lateral-flexion-press-nc0838', 'neck-rotation-nc0883');

delete from public.exercises
where is_system = true
  and slug in ('neck-rotation-nc0913', 'neck-rotation-nc0943', 'neck-rotation-nc0973', 'neck-rotation-press-nc0898', 'neck-rotation-press-nc0928', 'neck-rotation-press-nc0958', 'neck-rotation-press-nc0988', 'nordic-curl-hm0053', 'nordic-curl-hm0083', 'nordic-curl-hm0113', 'nordic-curl-hm0143', 'nordic-curl-hm0173', 'nordic-curl-hm0203', 'overhead-carry-bi0845', 'overhead-tricep-extension-tr0036', 'overhead-tricep-extension-tr0066', 'overhead-tricep-extension-tr0096', 'overhead-tricep-extension-tr0126', 'overhead-tricep-extension-tr0156', 'overhead-tricep-extension-tr0186', 'overhead-tricep-extension-tr0831', 'pallof-press-ch0046', 'pallof-press-ch0076', 'pallof-press-ch0106', 'pallof-press-ch0136', 'pallof-press-ch0166', 'pallof-press-ch0196', 'pallof-press-co0236', 'pallof-press-co0266', 'pallof-press-co0296', 'pallof-press-co0326', 'pallof-press-co0356', 'pallof-press-co0386', 'pallof-press-co0416', 'pause-squat-la0903', 'pause-squat-la0933', 'pause-squat-la0963', 'pause-squat-la0993', 'plate-pinch-walk-fa0477', 'plate-pinch-walk-fa0507');

delete from public.exercises
where is_system = true
  and slug in ('plate-pinch-walk-fa0537', 'plate-pinch-walk-fa0567', 'plate-pinch-walk-fa0597', 'plate-pinch-walk-fa0627', 'poliquin-step-up-qd0892', 'poliquin-step-up-qd0922', 'poliquin-step-up-qd0952', 'poliquin-step-up-qd0982', 'rear-delt-fly-sh0439', 'rear-delt-fly-sh0454', 'rear-delt-fly-sh0469', 'rear-delt-fly-sh0484', 'rear-delt-fly-sh0499', 'rear-delt-fly-sh0514', 'rear-delt-fly-sh0529', 'rear-delt-fly-sh0544', 'rear-delt-fly-sh0559', 'rear-delt-fly-sh0574', 'rear-delt-fly-sh0589', 'rear-delt-fly-sh0604', 'rear-delt-fly-sh0619', 'reverse-fly-sh0244', 'reverse-fly-sh0274', 'reverse-fly-sh0304', 'reverse-fly-sh0334', 'reverse-fly-sh0364', 'reverse-fly-sh0394', 'reverse-hyper-hm0458', 'reverse-hyper-hm0488', 'reverse-hyper-hm0518', 'reverse-hyper-hm0548', 'reverse-hyper-hm0578', 'reverse-hyper-hm0608', 'reverse-lunge-qd0247', 'reverse-lunge-qd0277', 'reverse-lunge-qd0307', 'reverse-lunge-qd0337', 'reverse-lunge-qd0367', 'reverse-lunge-qd0397', 'rope-overhead-extension-tr0456');

delete from public.exercises
where is_system = true
  and slug in ('rope-overhead-extension-tr0486', 'rope-overhead-extension-tr0516', 'rope-overhead-extension-tr0546', 'rope-overhead-extension-tr0576', 'rope-overhead-extension-tr0606', 'rowing-ca0344', 'rowing-ca0374', 'rowing-ca0404', 'rowing-intervals-ca0389', 'rowing-intervals-ca0419', 'running-ca0134', 'running-ca0164', 'running-ca0194', 'running-intervals-ca0179', 'running-intervals-ca0209', 'russian-twist-co0056', 'russian-twist-co0086', 'russian-twist-co0116', 'russian-twist-co0146', 'russian-twist-co0176', 'russian-twist-co0206', 'scapular-wall-slide-sh0874', 'scapular-wall-slide-sh0904', 'scapular-wall-slide-sh0934', 'scapular-wall-slide-sh0964', 'scapular-wall-slide-sh0994', 'seated-calf-hold-walk-cv0475', 'seated-calf-hold-walk-cv0505', 'seated-calf-hold-walk-cv0535', 'seated-calf-hold-walk-cv0565', 'seated-calf-hold-walk-cv0595', 'seated-calf-hold-walk-cv0625', 'seated-good-morning-hm0878', 'seated-good-morning-hm0908', 'seated-good-morning-hm0938', 'seated-good-morning-hm0968', 'seated-good-morning-hm0998', 'single-arm-tricep-extension-tr0246', 'single-arm-tricep-extension-tr0276', 'single-arm-tricep-extension-tr0306');

delete from public.exercises
where is_system = true
  and slug in ('single-arm-tricep-extension-tr0336', 'single-arm-tricep-extension-tr0366', 'single-arm-tricep-extension-tr0396', 'single-leg-calf-walk-cv0265', 'single-leg-calf-walk-cv0295', 'single-leg-calf-walk-cv0325', 'single-leg-calf-walk-cv0355', 'single-leg-calf-walk-cv0385', 'single-leg-calf-walk-cv0415', 'single-leg-hip-thrust-gl0474', 'single-leg-hip-thrust-gl0504', 'single-leg-hip-thrust-gl0534', 'single-leg-hip-thrust-gl0564', 'single-leg-hip-thrust-gl0594', 'single-leg-hip-thrust-gl0624', 'sissy-squat-hm0863', 'sissy-squat-hm0893', 'sissy-squat-hm0923', 'sissy-squat-hm0953', 'sissy-squat-hm0983', 'sissy-squat-qd0262', 'sissy-squat-qd0292', 'sissy-squat-qd0322', 'sissy-squat-qd0352', 'sissy-squat-qd0382', 'sissy-squat-qd0412', 'slider-hamstring-curl-hm0263', 'slider-hamstring-curl-hm0293', 'slider-hamstring-curl-hm0323', 'slider-hamstring-curl-hm0353', 'slider-hamstring-curl-hm0383', 'slider-hamstring-curl-hm0413', 'smith-close-grip-press-ch0781', 'smith-floor-press-ch0991', 'spanish-squat-qd0682', 'spanish-squat-qd0712', 'spanish-squat-qd0742', 'spanish-squat-qd0772', 'spanish-squat-qd0802', 'spanish-squat-qd0832');

delete from public.exercises
where is_system = true
  and slug in ('step-up-qd0877', 'step-up-qd0907', 'step-up-qd0937', 'step-up-qd0967', 'step-up-qd0997', 'straight-arm-pulldown-ba0482', 'straight-arm-pulldown-la0438', 'swimming-ca0764', 'swimming-ca0794', 'swimming-ca0824', 'swimming-intervals-ca0809', 'swimming-intervals-ca0839', 'terminal-knee-extension-qd0472', 'terminal-knee-extension-qd0502', 'terminal-knee-extension-qd0532', 'terminal-knee-extension-qd0562', 'terminal-knee-extension-qd0592', 'terminal-knee-extension-qd0622', 'thruster-fu0270', 'thruster-fu0300', 'thruster-fu0330', 'thruster-fu0360', 'thruster-fu0390', 'thruster-fu0420', 'thruster-fu0915', 'trap-bar-close-grip-press-ch0541', 'trap-bar-floor-press-tr0891', 'typewriter-pull-up-ba0842', 'walking-lunge-ba0407', 'walking-lunge-qd0037', 'walking-lunge-qd0067', 'walking-lunge-qd0097', 'walking-lunge-qd0127', 'walking-lunge-qd0157', 'walking-lunge-qd0187', 'weighted-calf-march-cv0685', 'weighted-calf-march-cv0715', 'weighted-calf-march-cv0745', 'weighted-calf-march-cv0775', 'weighted-calf-march-cv0805');

delete from public.exercises
where is_system = true
  and slug in ('weighted-calf-march-cv0835', 'wide-lat-pulldown-la0678', 'wrist-roller-walk-fa0057', 'wrist-roller-walk-fa0087', 'wrist-roller-walk-fa0117', 'wrist-roller-walk-fa0147', 'wrist-roller-walk-fa0177', 'wrist-roller-walk-fa0207', 'y-raise-sh0889', 'y-raise-sh0919', 'y-raise-sh0949', 'y-raise-sh0979');

drop table if exists public._migration_exercise_slug_remap;

create unique index if not exists exercises_system_unique_name_idx
  on public.exercises (lower(trim(name)))
  where is_system = true;
